import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { useAuth } from "@/hooks/use-auth";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";

type Language = "en" | "fr" | "nl";

type TranslationKey = 
  | "home" | "expenses" | "goals" | "family" | "shared" | "settings"
  | "group" | "dashboard" | "groupMembers" | "groupType" | "groupName"
  | "roommates" | "couple" | "member"
  | "settlement" | "settleDebt" | "balanceBoard" | "youOwe" | "owesYou" | "settled" | "recordSettlement"
  | "splitEqual" | "splitCustom" | "splitPercentage" | "paidBy" | "splitBetween" | "splitMethod" | "selectMembers"
  | "totalGroupSpending" | "noGroupYet" | "createOrJoinGroup" | "inviteCode" | "showQrCode" | "hideQrCode"
  | "scanQrCode" | "pointCamera" | "cameraPermissionDenied" | "cameraUnavailable" | "close"
  | "leaveGroup" | "confirmLeaveGroup"
  | "signOut" | "profile" | "language" | "english" | "french" | "dutch"
  | "spendingBreakdown" | "recentActivity" | "viewAll" | "totalSpent"
  | "thisMonth" | "thisWeek" | "topGoal" | "noGoalsYet" | "setGoal"
  | "noTransactions" | "save" | "cancel" | "edit" | "delete"
  | "profileName" | "profileImage" | "changeImage" | "settingsTitle"
  | "spendingReflections" | "weeklyReflections" | "monthlyReflections"
  | "spentThisWeek" | "spentThisMonth" | "topCategory" | "noData"
  | "viewSpendingReflections" | "financialSnapshot" | "hi"
  | "priority" | "daysLeft" | "dueToday" | "viewAllGoals" | "categoryDetails"
  | "profileUpdated" | "changesSaved" | "error" | "failedToUpdate" | "yourName"
  | "imageUrlPlaceholder" | "currency" | "scanReceipt" | "scanning" | "confirmDetails"
  | "extractedFromReceipt" | "useThisData" | "tryAgain"
  | "selectCurrency" | "currencyPromptMessage" | "confirmCurrency"
  | "dangerZone" | "deleteAccountWarning" | "deleteAccount" | "confirmDeleteAccount"
  | "deleteAccountPermanent" | "typeDeleteToConfirm" | "deleteAccountPermanently"
  | "accountDeleted" | "accountDeletedMessage" | "failedToDeleteAccount"
  | "expenseCategories" | "customizeCategoriesDescription" | "newCategoryPlaceholder"
  | "categories" | "resetToDefault" | "categoriesUpdated" | "customizeCategoriesHint"
  | "paidWith" | "myMoney" | "familyMoney" | "reports" | "monthlyReport" | "weeklyReport"
  | "viewReports" | "noExpensesInPeriod" | "allCategories" | "backToReports"
  | "previousMonth" | "nextMonth" | "previousWeek" | "nextWeek" | "expensesInCategory"
  | "expense" | "expensesPlural" | "personal" | "familyBadge"
  | "familyDashboard" | "groupDashboard" | "members" | "month" | "week" | "sharedSpending"
  | "moneySourceSplit" | "familyMoneySource" | "personalMoneySource"
  | "noSharedExpenses" | "backToCategories" | "noExpensesInCategory"
  | "spendingByCategory" | "familyGoals" | "groupGoals" | "recentSharedExpenses"
  | "statusCompleted" | "statusOnTrack" | "statusSlightlyBehind" | "statusBehind" | "priorityLabel"
  | "messages" | "savedNotes" | "typeMessage" | "send" | "noMessages" | "startConversation"
  | "addNote" | "noteTitlePlaceholder" | "noteContentPlaceholder" | "noNotes" | "addFirstNote"
  | "deleteNote" | "markComplete" | "markIncomplete" | "noteDeleted" | "messageSent" | "noteSaved"
  | "shoppingList" | "by" | "noGoals"
  | "notifications" | "dailyReminder" | "dailyReminderDescription" | "reminderTime"
  | "weeklyReminder" | "weeklyReminderDescription" | "monthlyReminder" | "monthlyReminderDescription"
  | "budgetAlerts" | "budgetAlertsDescription"
  | "notificationsEnabled" | "notificationsDisabled" | "enableNotifications"
  | "notificationPermissionDenied" | "makeAdmin" | "removeAdmin" | "adminPromoted"
  | "adminDemoted" | "maxAdminsReached" | "confirmMakeAdmin" | "confirmRemoveAdmin" | "reminderUpdated"
  | "everydayExpenses" | "recurringExpenses" | "recurring" | "addRecurring" | "editRecurring"
  | "recurringName" | "recurringAmount" | "recurringCategory" | "recurringFrequency"
  | "recurringNote" | "noRecurringExpenses" | "addFirstRecurring" | "totalRecurring"
  | "subscriptions" | "utilities" | "taxes" | "insurance" | "other"
  | "monthly" | "quarterly" | "yearly" | "perMonth" | "perQuarter" | "perYear"
  | "recurringAdded" | "recurringUpdated" | "recurringDeleted" | "activeLabel" | "pausedLabel"
  | "recurringCategoriesTitle" | "recurringCategoriesDescription" | "recurringCategoriesUpdated"
  | "newRecurringCategoryPlaceholder" | "customizeRecurringCategoriesHint"
  | "budgetPlanning" | "planYourBudget" | "budgetSetupMessage"
  | "setupNow" | "remindWeek" | "remindMonth"
  | "totalBudget" | "totalRemaining" | "percentUsed" | "spent"
  | "remaining" | "budgetAmount" | "periodType" | "weekly"
  | "editBudget" | "addBudget" | "deleteBudget" | "noBudgets" | "setupFirstBudget"
  | "budgetAdded" | "budgetUpdated" | "budgetDeleted"
  | "thresholds" | "threshold50" | "threshold60" | "threshold80" | "threshold100"
  | "budgetNote" | "budgetNotePlaceholder" | "averageSpending"
  | "budgetOverview" | "categoryBudgets" | "noBudgetSet" | "addBudgetForCategory"
  | "budgetExceeded" | "onBudget" | "overBudget" | "budgetWarning"
  | "personalSpending" | "today" | "vsLastMonth"
  | "spendingActivity" | "weeklyView" | "monthlyView"
  | "sun" | "mon" | "tue" | "wed" | "thu" | "fri" | "sat"
  | "searchExpenses" | "noSearchResults"
  | "tapBarHint" | "nothingSpentHere" | "budget"
  | "landingHeroTitle1" | "landingHeroTitle2" | "landingHeroSubtitle" | "landingHeroNote"
  | "landingOpenApp" | "landingInstallApp"
  | "landingTrustTitle" | "landingTrustBody"
  | "landingWhyTitle" | "landingWhySubtitle"
  | "landingHowTitle" | "landingHowSubtitle"
  | "landingFeaturesTitle"
  | "landingGrowTitle" | "landingGrowBody"
  | "landingInstallTitle" | "landingInstallSubtitle"
  | "landingCurrencyTitle" | "landingCurrencyBody"
  | "landingFeedbackTitle" | "landingFeedbackSubtitle"
  | "landingSignIn"
  | "landingStep1Title" | "landingStep1Desc"
  | "landingStep2Title" | "landingStep2Desc"
  | "landingStep3Title" | "landingStep3Desc"
  | "landingStep4Title" | "landingStep4Desc"
  | "landingBeta"
  | "landingMockThisMonth" | "landingMockSpentAcross" | "landingMockYouOwe" | "landingMockOwedToYou"
  | "landingMockGroceries" | "landingMockUtilities" | "landingMockDiningOut"
  | "landingTrustSecure" | "landingTrustCloud" | "landingTrustCurrency" | "landingTrustMobile" | "landingTrustLanguages"
  | "landingUseFamiliesTitle" | "landingUseFamiliesDesc"
  | "landingUseRoommatesTitle" | "landingUseRoommatesDesc"
  | "landingUseCouplesTitle" | "landingUseCouplesDesc"
  | "landingUseFriendsTitle" | "landingUseFriendsDesc"
  | "landingUseSoloTitle" | "landingUseSoloDesc"
  | "landingFeature1Title" | "landingFeature1Desc"
  | "landingFeature2Title" | "landingFeature2Desc"
  | "landingFeature3Title" | "landingFeature3Desc"
  | "landingFeature4Title" | "landingFeature4Desc"
  | "landingFeature5Title" | "landingFeature5Desc"
  | "landingFeature6Title" | "landingFeature6Desc"
  | "landingGrowItem1Label" | "landingGrowItem1Detail"
  | "landingGrowItem2Label" | "landingGrowItem2Detail"
  | "landingGrowItem3Label" | "landingGrowItem3Detail"
  | "landingGrowItem4Label" | "landingGrowItem4Detail"
  | "landingGrowItem5Label" | "landingGrowItem5Detail"
  | "landingInstallIphoneTitle" | "landingInstallIphoneStep1" | "landingInstallIphoneStep2" | "landingInstallIphoneStep3" | "landingInstallIphoneStep4"
  | "landingInstallAndroidTitle" | "landingInstallAndroidStep1" | "landingInstallAndroidStep2" | "landingInstallAndroidStep3" | "landingInstallAndroidStep4"
  | "landingWhyInstallTitle"
  | "landingWhyInstall1Title" | "landingWhyInstall1Desc"
  | "landingWhyInstall2Title" | "landingWhyInstall2Desc"
  | "landingWhyInstall3Title" | "landingWhyInstall3Desc"
  | "landingWhyInstall4Title" | "landingWhyInstall4Desc"
  | "landingWhyNotAppStoreTitle" | "landingWhyNotAppStoreBody"
  | "landingFeedbackAlsoIn" | "landingFeedbackEmail"
  | "landingFormName" | "landingFormNamePlaceholder"
  | "landingFormEmailLabel" | "landingFormEmailPlaceholder"
  | "landingFormMessageLabel" | "landingFormMessagePlaceholder"
  | "landingFormSubmit" | "landingFormThankYou" | "landingFormThankYouDesc"
  | "landingComingSoonTitle" | "landingComingSoonSubtitle"
  | "landingRoadmap1" | "landingRoadmap2" | "landingRoadmap3" | "landingRoadmap4" | "landingRoadmap5" | "landingRoadmap6"
  | "landingCtaTitle" | "landingCtaSubtitle" | "landingCtaNote"
  | "landingFooterText" | "landingFooterAvailable";

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    home: "Home",
    expenses: "Expenses",
    goals: "Goals",
    family: "Family",
    shared: "Shared",
    settings: "Settings",
    group: "Group",
    dashboard: "Dashboard",
    groupMembers: "Group Members",
    groupType: "Group Type",
    groupName: "Group Name",
    roommates: "Roommates",
    couple: "Couple",
    member: "Member",
    settlement: "Settlement",
    settleDebt: "Settle Debt",
    balanceBoard: "Balance Board",
    youOwe: "You owe",
    owesYou: "owes you",
    settled: "Settled",
    recordSettlement: "Record Settlement",
    splitEqual: "Split Equally",
    splitCustom: "Custom Amounts",
    splitPercentage: "By Percentage",
    paidBy: "Paid by",
    splitBetween: "Split between",
    splitMethod: "Split Method",
    selectMembers: "Select members",
    totalGroupSpending: "Total Group Spending",
    noGroupYet: "No group yet",
    createOrJoinGroup: "Create or join a group to get started",
    inviteCode: "Invite Code",
    showQrCode: "Show QR Code",
    hideQrCode: "Hide QR Code",
    scanQrCode: "Scan QR Code",
    pointCamera: "Point your camera at the QR code",
    cameraPermissionDenied: "Camera permission was denied. Please allow camera access and try again, or type the code manually.",
    cameraUnavailable: "Could not access camera. Please type the invite code manually.",
    close: "Close",
    leaveGroup: "Leave Group",
    confirmLeaveGroup: "Are you sure you want to leave this group? Your personal data will be kept.",
    signOut: "Sign Out",
    profile: "Profile",
    language: "Language",
    english: "English",
    french: "French",
    dutch: "Dutch",
    spendingBreakdown: "Spending Breakdown",
    recentActivity: "Recent Activity",
    viewAll: "View All",
    totalSpent: "Total Spent",
    thisMonth: "this month",
    thisWeek: "this week",
    topGoal: "Top Goal",
    noGoalsYet: "No savings goals yet",
    setGoal: "Set a Goal",
    noTransactions: "No transactions found.",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    profileName: "Display Name",
    profileImage: "Profile Image",
    changeImage: "Change Image",
    settingsTitle: "Settings",
    spendingReflections: "Spending Reflections",
    weeklyReflections: "Weekly Summary",
    monthlyReflections: "Monthly Summary",
    spentThisWeek: "Spent This Week",
    spentThisMonth: "Spent This Month",
    topCategory: "Top Category",
    noData: "No spending data yet.",
    viewSpendingReflections: "View Spending Reflections",
    financialSnapshot: "Here's your financial snapshot.",
    hi: "Hi",
    priority: "Priority",
    daysLeft: "days left",
    dueToday: "Due today!",
    viewAllGoals: "View All Goals",
    categoryDetails: "Category Details",
    profileUpdated: "Profile updated",
    changesSaved: "Your changes have been saved.",
    error: "Error",
    failedToUpdate: "Failed to update profile.",
    yourName: "Your name",
    imageUrlPlaceholder: "Image URL (optional)",
    currency: "Currency",
    scanReceipt: "Scan Receipt",
    scanning: "Scanning...",
    confirmDetails: "Confirm Details",
    extractedFromReceipt: "Extracted from receipt",
    useThisData: "Use This Data",
    tryAgain: "Try Again",
    selectCurrency: "Select Your Currency",
    currencyPromptMessage: "Choose the currency you'll use for tracking expenses. You can change this anytime in Settings.",
    confirmCurrency: "Confirm Currency",
    dangerZone: "Danger Zone",
    deleteAccountWarning: "Once you delete your account, there is no going back. All your data will be permanently removed.",
    deleteAccount: "Delete Account",
    confirmDeleteAccount: "Delete Your Account?",
    deleteAccountPermanent: "This action cannot be undone. All your expenses, goals, and data will be permanently deleted.",
    typeDeleteToConfirm: 'Type "DELETE" to confirm:',
    deleteAccountPermanently: "Delete Account Permanently",
    accountDeleted: "Account Deleted",
    accountDeletedMessage: "Your account has been permanently deleted.",
    failedToDeleteAccount: "Failed to delete account. Please try again.",
    expenseCategories: "Expense Categories",
    customizeCategoriesDescription: "Customize the categories for tracking your expenses. Click a category to edit its name.",
    newCategoryPlaceholder: "Add new category...",
    categories: "categories",
    resetToDefault: "Reset to Default",
    categoriesUpdated: "Categories Updated",
    customizeCategoriesHint: "Customize categories in Settings",
    paidWith: "Paid With",
    myMoney: "My Money",
    familyMoney: "Group Money",
    reports: "Reports",
    monthlyReport: "Monthly Report",
    weeklyReport: "Weekly Report",
    viewReports: "View Reports",
    noExpensesInPeriod: "No expenses in this period",
    allCategories: "All Categories",
    backToReports: "Back to Reports",
    previousMonth: "Previous Month",
    nextMonth: "Next Month",
    previousWeek: "Previous Week",
    nextWeek: "Next Week",
    expensesInCategory: "Expenses in",
    expense: "expense",
    expensesPlural: "expenses",
    personal: "Personal",
    familyBadge: "Group",
    familyDashboard: "Group Dashboard",
    groupDashboard: "Group Dashboard",
    members: "members",
    month: "Month",
    week: "Week",
    sharedSpending: "Shared Spending",
    moneySourceSplit: "Money Source Split",
    familyMoneySource: "Group Money",
    personalMoneySource: "Personal Money",
    noSharedExpenses: "No shared expenses yet",
    backToCategories: "Back to Categories",
    noExpensesInCategory: "No expenses in this category",
    spendingByCategory: "Spending by Category",
    familyGoals: "Group Goals",
    groupGoals: "Group Goals",
    recentSharedExpenses: "Recent Shared Expenses",
    statusCompleted: "Completed",
    statusOnTrack: "On Track",
    statusSlightlyBehind: "Slightly Behind",
    statusBehind: "Behind",
    priorityLabel: "Priority",
    messages: "Messages",
    savedNotes: "Saved Notes",
    typeMessage: "Type a message...",
    send: "Send",
    noMessages: "No messages yet",
    startConversation: "Start a conversation with your group",
    addNote: "Add Note",
    noteTitlePlaceholder: "Note title (e.g. Shopping list)",
    noteContentPlaceholder: "Details (optional)",
    noNotes: "No saved notes",
    addFirstNote: "Add a note like a shopping list or reminder",
    deleteNote: "Delete Note",
    markComplete: "Mark complete",
    markIncomplete: "Mark incomplete",
    noteDeleted: "Note deleted",
    messageSent: "Message sent",
    noteSaved: "Note saved",
    shoppingList: "Shopping List",
    by: "by",
    noGoals: "No shared goals yet",
    notifications: "Notifications",
    dailyReminder: "Daily Expense Reminder",
    dailyReminderDescription: "Get reminded to log your expenses",
    reminderTime: "Reminder Time",
    weeklyReminder: "Weekly Summary",
    weeklyReminderDescription: "Review your weekly spending every Sunday",
    monthlyReminder: "Monthly Summary",
    monthlyReminderDescription: "Review your monthly spending at month end",
    budgetAlerts: "Budget Alerts",
    budgetAlertsDescription: "Get notified when you're close to or over a budget limit",
    notificationsEnabled: "Notifications enabled",
    notificationsDisabled: "Notifications disabled",
    enableNotifications: "Enable Notifications",
    notificationPermissionDenied: "Notification permission denied. Please enable in browser settings.",
    makeAdmin: "Make Admin",
    removeAdmin: "Remove Admin",
    adminPromoted: "Member promoted to admin",
    adminDemoted: "Admin role removed",
    maxAdminsReached: "Maximum of 2 admins per group",
    confirmMakeAdmin: "Make this member an admin? They will have the same permissions as you.",
    confirmRemoveAdmin: "Remove admin role from this member?",
    reminderUpdated: "Reminder settings updated",
    everydayExpenses: "Everyday Expenses",
    recurringExpenses: "Recurring Expenses",
    recurring: "Recurring",
    addRecurring: "Add Recurring Expense",
    editRecurring: "Edit Recurring Expense",
    recurringName: "Name",
    recurringAmount: "Amount",
    recurringCategory: "Group",
    recurringFrequency: "Frequency",
    recurringNote: "Note (optional)",
    noRecurringExpenses: "No recurring expenses yet",
    addFirstRecurring: "Track subscriptions, utilities, taxes and other fixed costs",
    totalRecurring: "Total Recurring",
    subscriptions: "Subscriptions",
    utilities: "Utilities",
    taxes: "Taxes",
    insurance: "Insurance",
    other: "Other",
    monthly: "Monthly",
    quarterly: "Quarterly",
    yearly: "Yearly",
    perMonth: "/month",
    perQuarter: "/quarter",
    perYear: "/year",
    recurringAdded: "Recurring expense added",
    recurringUpdated: "Recurring expense updated",
    recurringDeleted: "Recurring expense deleted",
    activeLabel: "Active",
    pausedLabel: "Paused",
    recurringCategoriesTitle: "Recurring Expense Groups",
    recurringCategoriesDescription: "Customize the groups for organizing your recurring expenses. Click a group to edit its name.",
    recurringCategoriesUpdated: "Recurring Groups Updated",
    newRecurringCategoryPlaceholder: "Add new group...",
    customizeRecurringCategoriesHint: "Customize groups in Settings",
    budgetPlanning: "Budget & Planning",
    planYourBudget: "Plan Your Budget",
    budgetSetupMessage: "Would you like to set up your budgets now, or after tracking your spending for a while?",
    setupNow: "Set Up Now",
    remindWeek: "Remind Me in One Week",
    remindMonth: "Remind Me in One Month",
    totalBudget: "Total Budget",
    totalRemaining: "Total Remaining",
    percentUsed: "used",
    spent: "Spent",
    remaining: "Remaining",
    budgetAmount: "Budget Amount",
    periodType: "Period",
    weekly: "Weekly",
    editBudget: "Edit Budget",
    addBudget: "Add Budget",
    deleteBudget: "Delete Budget",
    noBudgets: "No budgets set up yet",
    setupFirstBudget: "Set up your first budget",
    budgetAdded: "Budget added",
    budgetUpdated: "Budget updated",
    budgetDeleted: "Budget deleted",
    thresholds: "Alert Thresholds",
    threshold50: "50% used",
    threshold60: "60% used",
    threshold80: "80% used",
    threshold100: "100% used",
    budgetNote: "Budget Note",
    budgetNotePlaceholder: "Add a planning note...",
    averageSpending: "Average Spending",
    budgetOverview: "Budget Overview",
    categoryBudgets: "Category Budgets",
    noBudgetSet: "No budget set",
    addBudgetForCategory: "Add budget",
    budgetExceeded: "Budget exceeded",
    onBudget: "On budget",
    overBudget: "Over budget",
    budgetWarning: "Budget warning",
    personalSpending: "Personal Spending",
    today: "Today",
    vsLastMonth: "vs last month",
    spendingActivity: "Spending Activity",
    weeklyView: "Weekly",
    monthlyView: "Monthly",
    sun: "Sun",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    searchExpenses: "Search expenses...",
    noSearchResults: "No expenses matching",
    tapBarHint: "Tap a bar to see its expenses",
    nothingSpentHere: "Nothing spent here",
    budget: "Budget",
    landingBeta: "Beta · Free while we're building",
    landingHeroTitle1: "Shared finances,",
    landingHeroTitle2: "finally simple.",
    landingHeroSubtitle: "Track expenses, split bills, and manage budgets together, whether you live with family, roommates, or a partner. Works like an app, installs from your browser.",
    landingHeroNote: "Start on your own, or join a group anytime.",
    landingOpenApp: "Open App",
    landingInstallApp: "Install App",
    landingSignIn: "Sign In",
    landingTrustTitle: "Built for real life, not spreadsheets",
    landingTrustBody: "SharedLedger is a progressive web app, so no app store needed. Add it to your home screen in seconds. Share a group invite or the app itself via QR code or link, straight from WhatsApp, iMessage, or any messaging app. Your data is stored securely in the cloud.",
    landingWhyTitle: "Who is SharedLedger for?",
    landingWhySubtitle: "From couples to households to solo budgeters, it flexes to fit you.",
    landingHowTitle: "Up and running in minutes",
    landingHowSubtitle: "No complex setup. No credit card. No friction.",
    landingStep1Title: "Create a free account",
    landingStep1Desc: "Sign up in under 30 seconds with your email or Google account. No payment info required.",
    landingStep2Title: "Set up your group (optional)",
    landingStep2Desc: "Create a household or join one by scanning a QR code or tapping a share link sent via WhatsApp, iMessage, or any messaging app. Prefer to start solo? No problem, you can always add your group later.",
    landingStep3Title: "Add your first expense",
    landingStep3Desc: "Log any purchase instantly: pick a category, set an amount, choose a currency, and decide if it's shared or personal.",
    landingStep4Title: "Install as an app",
    landingStep4Desc: "Add SharedLedger to your home screen for the full native experience. No app store required. Works on iPhone and Android.",
    landingFeaturesTitle: "Everything you need to stay on track",
    landingGrowTitle: "Start simple. Grow with it.",
    landingGrowBody: "You don't need to set up a group on day one. Start tracking your own expenses solo and the app is fully useful right away. When you're ready, invite your household in one tap. Group features unlock naturally as you go.",
    landingInstallTitle: "Install SharedLedger on your phone",
    landingInstallSubtitle: "No app store. No downloads. Just add it to your home screen in seconds.",
    landingCurrencyTitle: "Works in your currency",
    landingCurrencyBody: "SharedLedger supports dozens of currencies including USD, EUR, GBP, CAD, AUD, JPY, INR, and many more. You can switch your currency any time in settings.",
    landingFeedbackTitle: "Share your thoughts",
    landingFeedbackSubtitle: "SharedLedger is in beta. Your feedback shapes what gets built next. Every message is read.",
    landingMockThisMonth: "This Month",
    landingMockSpentAcross: "spent across 3 members",
    landingMockYouOwe: "You owe",
    landingMockOwedToYou: "Owed to you",
    landingMockGroceries: "Groceries",
    landingMockUtilities: "Utilities",
    landingMockDiningOut: "Dining Out",
    landingTrustSecure: "Secure & Private",
    landingTrustCloud: "Cloud-Based",
    landingTrustCurrency: "Multi-Currency",
    landingTrustMobile: "Mobile-First",
    landingTrustLanguages: "3 Languages",
    landingUseFamiliesTitle: "Families",
    landingUseFamiliesDesc: "Track household spending, set budgets per category, and keep every family member aligned, from parents to kids.",
    landingUseRoommatesTitle: "Roommates",
    landingUseRoommatesDesc: "Split rent, groceries, and utilities fairly. See who paid what and settle up in seconds without the awkward conversations.",
    landingUseCouplesTitle: "Couples",
    landingUseCouplesDesc: "Manage shared expenses side by side. Set joint savings goals, track progress together, and stay financially in sync.",
    landingUseFriendsTitle: "Friend Groups",
    landingUseFriendsDesc: "Planning a trip, splitting dinners, or organising an outing? Create a group for any occasion, track who paid what, and settle up without the guesswork.",
    landingUseSoloTitle: "Solo Tracking",
    landingUseSoloDesc: "Don't share finances with anyone? SharedLedger works just as well on its own. Log expenses, set budgets, and track savings goals as a personal financial tracker.",
    landingFeature1Title: "Expense Tracking",
    landingFeature1Desc: "Log personal and shared expenses with categories, notes, and receipts. Filter and search your history instantly.",
    landingFeature2Title: "Smart Budgets",
    landingFeature2Desc: "Set monthly budgets per category. Colour-coded progress bars alert you before you overspend.",
    landingFeature3Title: "Savings Goals",
    landingFeature3Desc: "Create goals with targets and deadlines. Contribute over time and watch your progress grow.",
    landingFeature4Title: "Visual Reports",
    landingFeature4Desc: "Understand your spending patterns at a glance with charts, breakdowns, and trend analysis.",
    landingFeature5Title: "Smart Notifications",
    landingFeature5Desc: "Get reminders to log expenses and alerts when budgets hit your thresholds. Fully configurable.",
    landingFeature6Title: "Group Messaging",
    landingFeature6Desc: "Chat with your group right inside the app. Discuss expenses, ask questions, and stay in sync.",
    landingGrowItem1Label: "Solo tracking",
    landingGrowItem1Detail: "Available from day one",
    landingGrowItem2Label: "Budgets & goals",
    landingGrowItem2Detail: "Available from day one",
    landingGrowItem3Label: "Group expenses & splitting",
    landingGrowItem3Detail: "Unlocks when you join a group",
    landingGrowItem4Label: "Group messaging",
    landingGrowItem4Detail: "Unlocks when you join a group",
    landingGrowItem5Label: "Family dashboard",
    landingGrowItem5Detail: "Unlocks when you join a group",
    landingInstallIphoneTitle: "iPhone (Safari only)",
    landingInstallIphoneStep1: 'Got the link from WhatsApp or Snapchat? Tap the ··· menu or browser icon and select "Open in Safari" — this only works in Safari',
    landingInstallIphoneStep2: 'In Safari, go to sharedledger.app then tap the Share icon (□↑). It\'s at the bottom of the screen — or top-right if you use the compact address bar',
    landingInstallIphoneStep3: 'Scroll down the share menu and tap "Add to Home Screen"',
    landingInstallIphoneStep4: 'Tap "Add" in the top-right corner — the app icon will appear on your home screen',
    landingInstallAndroidTitle: "Android (Chrome)",
    landingInstallAndroidStep1: "Open SharedLedger in Chrome",
    landingInstallAndroidStep2: "Tap the three-dot menu (⋮) in the top right",
    landingInstallAndroidStep3: '"Add to Home Screen" or "Install App"',
    landingInstallAndroidStep4: 'Tap "Add" to confirm and it will appear on your home screen instantly',
    landingWhyInstallTitle: "Why install instead of just using the website?",
    landingWhyInstall1Title: "Home screen access",
    landingWhyInstall1Desc: "Launch instantly like any native app, without the browser bar or typing URLs.",
    landingWhyInstall2Title: "Fast loading",
    landingWhyInstall2Desc: "The app loads instantly from your home screen with no browser startup needed.",
    landingWhyInstall3Title: "Push notifications",
    landingWhyInstall3Desc: "Get budget alerts and expense reminders delivered to your device.",
    landingWhyInstall4Title: "Full-screen experience",
    landingWhyInstall4Desc: "Hides browser chrome for a distraction-free, app-like interface.",
    landingWhyNotAppStoreTitle: "Why isn't it in the App Store?",
    landingWhyNotAppStoreBody: "SharedLedger is headed to the App Store and Play Store, but while we're in beta, we're using a PWA so we can ship improvements fast and act on your feedback in real time. No app store approval delays, no waiting for updates. You always have the latest version the moment we push it, and adding it to your home screen is just as easy.",
    landingFeedbackAlsoIn: "You can also send feedback directly from within the app settings once you're signed in.",
    landingFeedbackEmail: "Or reach us via email:",
    landingFormName: "Name",
    landingFormNamePlaceholder: "Your name",
    landingFormEmailLabel: "Email (optional)",
    landingFormEmailPlaceholder: "you@example.com",
    landingFormMessageLabel: "Your feedback",
    landingFormMessagePlaceholder: "What do you love? What's missing? What would make SharedLedger perfect for you?",
    landingFormSubmit: "Send Feedback",
    landingFormThankYou: "Thank you for your feedback!",
    landingFormThankYouDesc: "We read every message and appreciate you taking the time to share your thoughts.",
    landingComingSoonTitle: "Coming soon",
    landingComingSoonSubtitle: "We're actively building. Here's what's on the roadmap.",
    landingRoadmap1: "Improved receipt scanning with smarter AI categorisation",
    landingRoadmap2: "Optional bank account integration for automatic expense import",
    landingRoadmap3: "Smart shared spending",
    landingRoadmap4: "Support for multiple groups per user",
    landingRoadmap5: "Smart analytics for personalised financial suggestions and planning",
    landingRoadmap6: "iOS & Android native apps",
    landingCtaTitle: "Ready to take control of your shared finances?",
    landingCtaSubtitle: "Free during beta. No credit card required. Start in under a minute.",
    landingCtaNote: "Start on your own, or join a group anytime.",
    landingFooterText: "Beta · Free while we're building. Your feedback helps shape the product.",
    landingFooterAvailable: "Available in English, French and Dutch.",
  },
  fr: {
    home: "Accueil",
    expenses: "Dépenses",
    goals: "Objectifs",
    family: "Famille",
    shared: "Partagé",
    settings: "Paramètres",
    group: "Groupe",
    dashboard: "Tableau de bord",
    groupMembers: "Membres du groupe",
    groupType: "Type de groupe",
    groupName: "Nom du groupe",
    roommates: "Colocataires",
    couple: "Couple",
    member: "Membre",
    settlement: "Règlement",
    settleDebt: "Régler la dette",
    balanceBoard: "Tableau des soldes",
    youOwe: "Vous devez",
    owesYou: "vous doit",
    settled: "Réglé",
    recordSettlement: "Enregistrer un règlement",
    splitEqual: "Partager également",
    splitCustom: "Montants personnalisés",
    splitPercentage: "Par pourcentage",
    paidBy: "Payé par",
    splitBetween: "Répartir entre",
    splitMethod: "Méthode de partage",
    selectMembers: "Sélectionner les membres",
    totalGroupSpending: "Dépenses totales du groupe",
    noGroupYet: "Pas encore de groupe",
    createOrJoinGroup: "Créez ou rejoignez un groupe pour commencer",
    inviteCode: "Code d'invitation",
    showQrCode: "Afficher le QR Code",
    hideQrCode: "Masquer le QR Code",
    scanQrCode: "Scanner le QR Code",
    pointCamera: "Pointez votre caméra vers le QR code",
    cameraPermissionDenied: "L'accès à la caméra a été refusé. Veuillez autoriser l'accès et réessayer, ou saisir le code manuellement.",
    cameraUnavailable: "Impossible d'accéder à la caméra. Veuillez saisir le code d'invitation manuellement.",
    close: "Fermer",
    leaveGroup: "Quitter le groupe",
    confirmLeaveGroup: "Êtes-vous sûr de vouloir quitter ce groupe ? Vos données personnelles seront conservées.",
    signOut: "Déconnexion",
    profile: "Profil",
    language: "Langue",
    english: "Anglais",
    french: "Français",
    dutch: "Néerlandais",
    spendingBreakdown: "Répartition des dépenses",
    recentActivity: "Activité récente",
    viewAll: "Voir tout",
    totalSpent: "Total dépensé",
    thisMonth: "ce mois",
    thisWeek: "cette semaine",
    topGoal: "Objectif principal",
    noGoalsYet: "Pas encore d'objectifs d'épargne",
    setGoal: "Définir un objectif",
    noTransactions: "Aucune transaction trouvée.",
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    delete: "Supprimer",
    profileName: "Nom d'affichage",
    profileImage: "Image de profil",
    changeImage: "Changer l'image",
    settingsTitle: "Paramètres",
    spendingReflections: "Réflexions sur les dépenses",
    weeklyReflections: "Résumé hebdomadaire",
    monthlyReflections: "Résumé mensuel",
    spentThisWeek: "Dépensé cette semaine",
    spentThisMonth: "Dépensé ce mois",
    topCategory: "Catégorie principale",
    noData: "Pas encore de données de dépenses.",
    viewSpendingReflections: "Voir les réflexions sur les dépenses",
    financialSnapshot: "Voici votre aperçu financier.",
    hi: "Bonjour",
    priority: "Priorité",
    daysLeft: "jours restants",
    dueToday: "Échéance aujourd'hui!",
    viewAllGoals: "Voir tous les objectifs",
    categoryDetails: "Détails par catégorie",
    profileUpdated: "Profil mis à jour",
    changesSaved: "Vos modifications ont été enregistrées.",
    error: "Erreur",
    failedToUpdate: "Impossible de mettre à jour le profil.",
    yourName: "Votre nom",
    imageUrlPlaceholder: "URL de l'image (optionnel)",
    currency: "Devise",
    scanReceipt: "Scanner le reçu",
    scanning: "Numérisation...",
    confirmDetails: "Confirmer les détails",
    extractedFromReceipt: "Extrait du reçu",
    useThisData: "Utiliser ces données",
    tryAgain: "Réessayer",
    selectCurrency: "Sélectionnez votre devise",
    currencyPromptMessage: "Choisissez la devise que vous utiliserez pour suivre vos dépenses. Vous pouvez la modifier à tout moment dans les Paramètres.",
    confirmCurrency: "Confirmer la devise",
    dangerZone: "Zone de danger",
    deleteAccountWarning: "Une fois votre compte supprimé, il n'y a pas de retour en arrière. Toutes vos données seront définitivement supprimées.",
    deleteAccount: "Supprimer le compte",
    confirmDeleteAccount: "Supprimer votre compte?",
    deleteAccountPermanent: "Cette action est irréversible. Toutes vos dépenses, objectifs et données seront définitivement supprimés.",
    typeDeleteToConfirm: 'Tapez "DELETE" pour confirmer:',
    deleteAccountPermanently: "Supprimer le compte définitivement",
    accountDeleted: "Compte supprimé",
    accountDeletedMessage: "Votre compte a été définitivement supprimé.",
    failedToDeleteAccount: "Échec de la suppression du compte. Veuillez réessayer.",
    expenseCategories: "Catégories de dépenses",
    customizeCategoriesDescription: "Personnalisez les catégories pour suivre vos dépenses. Cliquez sur une catégorie pour modifier son nom.",
    newCategoryPlaceholder: "Ajouter une catégorie...",
    categories: "catégories",
    resetToDefault: "Réinitialiser",
    categoriesUpdated: "Catégories mises à jour",
    customizeCategoriesHint: "Personnalisez les catégories dans Paramètres",
    paidWith: "Payé avec",
    myMoney: "Mon argent",
    familyMoney: "Argent du groupe",
    reports: "Rapports",
    monthlyReport: "Rapport mensuel",
    weeklyReport: "Rapport hebdomadaire",
    viewReports: "Voir les rapports",
    noExpensesInPeriod: "Aucune dépense pour cette période",
    allCategories: "Toutes les catégories",
    backToReports: "Retour aux rapports",
    previousMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    previousWeek: "Semaine précédente",
    nextWeek: "Semaine suivante",
    expensesInCategory: "Dépenses en",
    expense: "dépense",
    expensesPlural: "dépenses",
    personal: "Personnel",
    familyBadge: "Groupe",
    familyDashboard: "Tableau de bord du groupe",
    groupDashboard: "Tableau de bord du groupe",
    members: "membres",
    month: "Mois",
    week: "Semaine",
    sharedSpending: "Dépenses partagées",
    moneySourceSplit: "Répartition des sources",
    familyMoneySource: "Argent du groupe",
    personalMoneySource: "Argent personnel",
    noSharedExpenses: "Pas encore de dépenses partagées",
    backToCategories: "Retour aux catégories",
    noExpensesInCategory: "Aucune dépense dans cette catégorie",
    spendingByCategory: "Dépenses par catégorie",
    familyGoals: "Objectifs du groupe",
    groupGoals: "Objectifs du groupe",
    recentSharedExpenses: "Dépenses partagées récentes",
    statusCompleted: "Terminé",
    statusOnTrack: "En bonne voie",
    statusSlightlyBehind: "Légèrement en retard",
    statusBehind: "En retard",
    priorityLabel: "Priorité",
    messages: "Messages",
    savedNotes: "Notes sauvegardées",
    typeMessage: "Écrire un message...",
    send: "Envoyer",
    noMessages: "Aucun message",
    startConversation: "Commencez une conversation avec votre groupe",
    addNote: "Ajouter une note",
    noteTitlePlaceholder: "Titre (ex. Liste de courses)",
    noteContentPlaceholder: "Détails (optionnel)",
    noNotes: "Aucune note sauvegardée",
    addFirstNote: "Ajoutez une note comme une liste de courses ou un rappel",
    deleteNote: "Supprimer la note",
    markComplete: "Marquer comme terminé",
    markIncomplete: "Marquer comme non terminé",
    noteDeleted: "Note supprimée",
    messageSent: "Message envoyé",
    noteSaved: "Note sauvegardée",
    shoppingList: "Liste de courses",
    by: "par",
    noGoals: "Pas encore d'objectifs partagés",
    notifications: "Notifications",
    dailyReminder: "Rappel quotidien des dépenses",
    dailyReminderDescription: "Recevez un rappel pour enregistrer vos dépenses",
    reminderTime: "Heure du rappel",
    weeklyReminder: "Résumé hebdomadaire",
    weeklyReminderDescription: "Consultez vos dépenses hebdomadaires chaque dimanche",
    monthlyReminder: "Résumé mensuel",
    monthlyReminderDescription: "Consultez vos dépenses mensuelles en fin de mois",
    budgetAlerts: "Alertes budgétaires",
    budgetAlertsDescription: "Soyez notifié lorsque vous approchez ou dépassez une limite budgétaire",
    notificationsEnabled: "Notifications activées",
    notificationsDisabled: "Notifications désactivées",
    enableNotifications: "Activer les notifications",
    notificationPermissionDenied: "Permission de notification refusée. Veuillez activer dans les paramètres du navigateur.",
    makeAdmin: "Nommer administrateur",
    removeAdmin: "Retirer administrateur",
    adminPromoted: "Membre promu administrateur",
    adminDemoted: "Rôle d'administrateur retiré",
    maxAdminsReached: "Maximum de 2 administrateurs par groupe",
    confirmMakeAdmin: "Nommer ce membre administrateur ? Il aura les mêmes permissions que vous.",
    confirmRemoveAdmin: "Retirer le rôle d'administrateur de ce membre ?",
    reminderUpdated: "Paramètres de rappel mis à jour",
    everydayExpenses: "Dépenses courantes",
    recurringExpenses: "Dépenses récurrentes",
    recurring: "Récurrent",
    addRecurring: "Ajouter une dépense récurrente",
    editRecurring: "Modifier la dépense récurrente",
    recurringName: "Nom",
    recurringAmount: "Montant",
    recurringCategory: "Groupe",
    recurringFrequency: "Fréquence",
    recurringNote: "Note (optionnel)",
    noRecurringExpenses: "Aucune dépense récurrente",
    addFirstRecurring: "Suivez les abonnements, factures, impôts et autres coûts fixes",
    totalRecurring: "Total récurrent",
    subscriptions: "Abonnements",
    utilities: "Services publics",
    taxes: "Impôts",
    insurance: "Assurance",
    other: "Autre",
    monthly: "Mensuel",
    quarterly: "Trimestriel",
    yearly: "Annuel",
    perMonth: "/mois",
    perQuarter: "/trimestre",
    perYear: "/an",
    recurringAdded: "Dépense récurrente ajoutée",
    recurringUpdated: "Dépense récurrente mise à jour",
    recurringDeleted: "Dépense récurrente supprimée",
    activeLabel: "Actif",
    pausedLabel: "En pause",
    recurringCategoriesTitle: "Groupes de dépenses récurrentes",
    recurringCategoriesDescription: "Personnalisez les groupes pour organiser vos dépenses récurrentes. Cliquez sur un groupe pour modifier son nom.",
    recurringCategoriesUpdated: "Groupes récurrents mis à jour",
    newRecurringCategoryPlaceholder: "Ajouter un nouveau groupe...",
    customizeRecurringCategoriesHint: "Personnaliser les groupes dans Paramètres",
    budgetPlanning: "Budget & Planification",
    planYourBudget: "Planifiez votre budget",
    budgetSetupMessage: "Souhaitez-vous configurer vos budgets maintenant ou après avoir suivi vos dépenses pendant un moment ?",
    setupNow: "Configurer maintenant",
    remindWeek: "Me rappeler dans une semaine",
    remindMonth: "Me rappeler dans un mois",
    totalBudget: "Budget total",
    totalRemaining: "Restant total",
    percentUsed: "utilisé",
    spent: "Dépensé",
    remaining: "Restant",
    budgetAmount: "Montant du budget",
    periodType: "Période",
    weekly: "Hebdomadaire",
    editBudget: "Modifier le budget",
    addBudget: "Ajouter un budget",
    deleteBudget: "Supprimer le budget",
    noBudgets: "Aucun budget configuré",
    setupFirstBudget: "Configurez votre premier budget",
    budgetAdded: "Budget ajouté",
    budgetUpdated: "Budget mis à jour",
    budgetDeleted: "Budget supprimé",
    thresholds: "Seuils d'alerte",
    threshold50: "50% utilisé",
    threshold60: "60% utilisé",
    threshold80: "80% utilisé",
    threshold100: "100% utilisé",
    budgetNote: "Note de budget",
    budgetNotePlaceholder: "Ajouter une note de planification...",
    averageSpending: "Dépenses moyennes",
    budgetOverview: "Aperçu du budget",
    categoryBudgets: "Budgets par catégorie",
    noBudgetSet: "Pas de budget défini",
    addBudgetForCategory: "Ajouter un budget",
    budgetExceeded: "Budget dépassé",
    onBudget: "Dans le budget",
    overBudget: "Hors budget",
    budgetWarning: "Alerte budget",
    personalSpending: "Dépenses personnelles",
    today: "Aujourd'hui",
    vsLastMonth: "vs mois dernier",
    spendingActivity: "Activité de dépenses",
    weeklyView: "Semaine",
    monthlyView: "Mois",
    sun: "Dim",
    mon: "Lun",
    tue: "Mar",
    wed: "Mer",
    thu: "Jeu",
    fri: "Ven",
    sat: "Sam",
    searchExpenses: "Rechercher des dépenses...",
    noSearchResults: "Aucune dépense correspondant à",
    tapBarHint: "Appuyez sur une barre pour voir ses dépenses",
    nothingSpentHere: "Rien dépensé ici",
    budget: "Budget",
    landingBeta: "Bêta · Gratuit pendant le développement",
    landingHeroTitle1: "Finances partagées,",
    landingHeroTitle2: "enfin simples.",
    landingHeroSubtitle: "Suivez vos dépenses, partagez les factures et gérez les budgets ensemble, que vous viviez en famille, en colocation ou en couple. Fonctionne comme une appli, s'installe depuis votre navigateur.",
    landingHeroNote: "Commencez seul ou rejoignez un groupe à tout moment.",
    landingOpenApp: "Ouvrir l'app",
    landingInstallApp: "Installer l'app",
    landingSignIn: "Se connecter",
    landingTrustTitle: "Conçu pour la vraie vie, pas pour les tableurs",
    landingTrustBody: "SharedLedger est une application web progressive, donc aucun app store nécessaire. Ajoutez-la à votre écran d'accueil en quelques secondes. Partagez une invitation de groupe ou l'appli elle-même via QR code ou lien, directement depuis WhatsApp, iMessage ou toute autre messagerie. Vos données sont stockées en toute sécurité dans le cloud.",
    landingWhyTitle: "Pour qui est SharedLedger ?",
    landingWhySubtitle: "Des couples aux ménages en passant par les budgétaires solo, il s'adapte à vous.",
    landingHowTitle: "Opérationnel en quelques minutes",
    landingHowSubtitle: "Pas de configuration complexe. Pas de carte bancaire. Pas de friction.",
    landingStep1Title: "Créez un compte gratuit",
    landingStep1Desc: "Inscrivez-vous en moins de 30 secondes avec votre e-mail ou compte Google. Aucune information de paiement requise.",
    landingStep2Title: "Configurez votre groupe (facultatif)",
    landingStep2Desc: "Créez un ménage ou rejoignez-en un en scannant un QR code ou en appuyant sur un lien partagé via WhatsApp, iMessage ou toute autre messagerie. Vous préférez commencer seul ? Pas de problème, vous pouvez toujours ajouter votre groupe plus tard.",
    landingStep3Title: "Ajoutez votre première dépense",
    landingStep3Desc: "Enregistrez tout achat instantanément : choisissez une catégorie, définissez un montant, sélectionnez une devise et décidez si c'est partagé ou personnel.",
    landingStep4Title: "Installez en tant qu'application",
    landingStep4Desc: "Ajoutez SharedLedger à votre écran d'accueil pour une expérience native complète. Aucun app store requis. Fonctionne sur iPhone et Android.",
    landingFeaturesTitle: "Tout ce dont vous avez besoin pour rester sur la bonne voie",
    landingGrowTitle: "Commencez simplement. Évoluez avec.",
    landingGrowBody: "Vous n'avez pas besoin de configurer un groupe dès le premier jour. Commencez à suivre vos dépenses en solo et l'application est immédiatement utile. Quand vous êtes prêt, invitez votre ménage en un tap.",
    landingInstallTitle: "Installez SharedLedger sur votre téléphone",
    landingInstallSubtitle: "Pas d'app store. Pas de téléchargements. Ajoutez-le simplement à votre écran d'accueil en quelques secondes.",
    landingCurrencyTitle: "Fonctionne dans votre devise",
    landingCurrencyBody: "SharedLedger prend en charge des dizaines de devises, notamment USD, EUR, GBP, CAD, AUD, JPY, INR, et bien d'autres. Vous pouvez changer votre devise à tout moment dans les paramètres.",
    landingFeedbackTitle: "Partagez vos impressions",
    landingFeedbackSubtitle: "SharedLedger est en version bêta. Vos retours façonnent ce qui sera développé ensuite. Chaque message est lu.",
    landingMockThisMonth: "Ce mois",
    landingMockSpentAcross: "dépensé entre 3 membres",
    landingMockYouOwe: "Vous devez",
    landingMockOwedToYou: "On vous doit",
    landingMockGroceries: "Courses",
    landingMockUtilities: "Services",
    landingMockDiningOut: "Restaurant",
    landingTrustSecure: "Sécurisé & Privé",
    landingTrustCloud: "Basé sur le cloud",
    landingTrustCurrency: "Multi-Devises",
    landingTrustMobile: "Mobile d'abord",
    landingTrustLanguages: "3 Langues",
    landingUseFamiliesTitle: "Familles",
    landingUseFamiliesDesc: "Suivez les dépenses du foyer, définissez des budgets par catégorie et gardez chaque membre de la famille aligné, des parents aux enfants.",
    landingUseRoommatesTitle: "Colocataires",
    landingUseRoommatesDesc: "Partagez équitablement le loyer, les courses et les factures. Voyez qui a payé quoi et réglez en quelques secondes sans les conversations gênantes.",
    landingUseCouplesTitle: "Couples",
    landingUseCouplesDesc: "Gérez les dépenses partagées côte à côte. Fixez des objectifs d'épargne communs, suivez les progrès ensemble et restez financièrement synchronisés.",
    landingUseFriendsTitle: "Groupes d'amis",
    landingUseFriendsDesc: "Planifiez un voyage, partagez des dîners ou organisez une sortie ? Créez un groupe pour n'importe quelle occasion, suivez qui a payé quoi et réglez sans devinettes.",
    landingUseSoloTitle: "Solo",
    landingUseSoloDesc: "Vous ne partagez pas vos finances avec quelqu'un ? SharedLedger fonctionne tout aussi bien seul. Enregistrez les dépenses, définissez des budgets et suivez vos objectifs d'épargne.",
    landingFeature1Title: "Suivi des dépenses",
    landingFeature1Desc: "Enregistrez les dépenses personnelles et partagées avec des catégories, des notes et des reçus. Filtrez et recherchez votre historique instantanément.",
    landingFeature2Title: "Budgets intelligents",
    landingFeature2Desc: "Définissez des budgets mensuels par catégorie. Des barres de progression codées par couleur vous alertent avant de dépasser.",
    landingFeature3Title: "Objectifs d'épargne",
    landingFeature3Desc: "Créez des objectifs avec des cibles et des délais. Contribuez au fil du temps et regardez vos progrès croître.",
    landingFeature4Title: "Rapports visuels",
    landingFeature4Desc: "Comprenez vos habitudes de dépenses en un coup d'œil avec des graphiques, des analyses et des tendances.",
    landingFeature5Title: "Notifications intelligentes",
    landingFeature5Desc: "Recevez des rappels pour enregistrer vos dépenses et des alertes lorsque les budgets atteignent vos seuils. Entièrement configurable.",
    landingFeature6Title: "Messagerie de groupe",
    landingFeature6Desc: "Discutez avec votre groupe directement dans l'application. Parlez de dépenses, posez des questions et restez synchronisés.",
    landingGrowItem1Label: "Suivi solo",
    landingGrowItem1Detail: "Disponible dès le premier jour",
    landingGrowItem2Label: "Budgets & objectifs",
    landingGrowItem2Detail: "Disponible dès le premier jour",
    landingGrowItem3Label: "Dépenses de groupe & partage",
    landingGrowItem3Detail: "Se débloque en rejoignant un groupe",
    landingGrowItem4Label: "Messagerie de groupe",
    landingGrowItem4Detail: "Se débloque en rejoignant un groupe",
    landingGrowItem5Label: "Tableau de bord familial",
    landingGrowItem5Detail: "Se débloque en rejoignant un groupe",
    landingInstallIphoneTitle: "iPhone (Safari uniquement)",
    landingInstallIphoneStep1: "Reçu le lien via WhatsApp ou Snapchat ? Appuyez sur ··· ou l'icône du navigateur et choisissez « Ouvrir dans Safari » — cela ne fonctionne que dans Safari",
    landingInstallIphoneStep2: "Dans Safari, allez sur sharedledger.app puis appuyez sur l'icône Partager (□↑). Elle se trouve en bas de l'écran — ou en haut à droite si vous utilisez la barre d'adresse compacte",
    landingInstallIphoneStep3: "Faites défiler le menu de partage et appuyez sur « Ajouter à l'écran d'accueil »",
    landingInstallIphoneStep4: "Appuyez sur « Ajouter » en haut à droite — l'icône apparaîtra sur votre écran d'accueil",
    landingInstallAndroidTitle: "Android (Chrome)",
    landingInstallAndroidStep1: "Ouvrez SharedLedger dans Chrome",
    landingInstallAndroidStep2: "Appuyez sur le menu à trois points (⋮) en haut à droite",
    landingInstallAndroidStep3: "« Ajouter à l'écran d'accueil » ou « Installer l'application »",
    landingInstallAndroidStep4: "Appuyez sur « Ajouter » pour confirmer et il apparaîtra sur votre écran d'accueil instantanément",
    landingWhyInstallTitle: "Pourquoi l'installer plutôt que d'utiliser le site web ?",
    landingWhyInstall1Title: "Accès depuis l'écran d'accueil",
    landingWhyInstall1Desc: "Lancez instantanément comme n'importe quelle application native, sans barre de navigateur ni URL à taper.",
    landingWhyInstall2Title: "Chargement rapide",
    landingWhyInstall2Desc: "L'application se charge instantanément depuis votre écran d'accueil sans démarrage du navigateur.",
    landingWhyInstall3Title: "Notifications push",
    landingWhyInstall3Desc: "Recevez des alertes budgétaires et des rappels de dépenses directement sur votre appareil.",
    landingWhyInstall4Title: "Expérience plein écran",
    landingWhyInstall4Desc: "Masque l'interface du navigateur pour une expérience sans distraction, similaire à une application native.",
    landingWhyNotAppStoreTitle: "Pourquoi n'est-il pas dans l'App Store ?",
    landingWhyNotAppStoreBody: "SharedLedger se dirige vers l'App Store et le Play Store, mais pendant la bêta, nous utilisons une PWA pour expédier rapidement les améliorations et agir sur vos retours en temps réel. Pas de délais d'approbation, pas d'attente pour les mises à jour. Vous avez toujours la dernière version dès que nous la publions.",
    landingFeedbackAlsoIn: "Vous pouvez également envoyer des commentaires directement depuis les paramètres de l'application une fois connecté.",
    landingFeedbackEmail: "Ou contactez-nous par e-mail :",
    landingFormName: "Nom",
    landingFormNamePlaceholder: "Votre nom",
    landingFormEmailLabel: "E-mail (optionnel)",
    landingFormEmailPlaceholder: "vous@exemple.com",
    landingFormMessageLabel: "Vos commentaires",
    landingFormMessagePlaceholder: "Qu'est-ce que vous aimez ? Qu'est-ce qui manque ? Qu'est-ce qui rendrait SharedLedger parfait pour vous ?",
    landingFormSubmit: "Envoyer",
    landingFormThankYou: "Merci pour vos commentaires !",
    landingFormThankYouDesc: "Nous lisons chaque message et apprécions que vous ayez pris le temps de partager vos réflexions.",
    landingComingSoonTitle: "Bientôt disponible",
    landingComingSoonSubtitle: "Nous construisons activement. Voici ce qui est sur la feuille de route.",
    landingRoadmap1: "Numérisation améliorée des reçus avec une catégorisation IA plus intelligente",
    landingRoadmap2: "Intégration optionnelle de compte bancaire pour l'import automatique des dépenses",
    landingRoadmap3: "Dépenses partagées intelligentes",
    landingRoadmap4: "Support de plusieurs groupes par utilisateur",
    landingRoadmap5: "Analyses intelligentes pour des suggestions et planifications financières personnalisées",
    landingRoadmap6: "Applications natives iOS & Android",
    landingCtaTitle: "Prêt à prendre le contrôle de vos finances partagées ?",
    landingCtaSubtitle: "Gratuit pendant la bêta. Aucune carte de crédit requise. Démarrez en moins d'une minute.",
    landingCtaNote: "Commencez seul, ou rejoignez un groupe à tout moment.",
    landingFooterText: "Bêta · Gratuit pendant le développement. Votre feedback aide à façonner le produit.",
    landingFooterAvailable: "Disponible en anglais, français et néerlandais.",
  },
  nl: {
    home: "Home",
    expenses: "Uitgaven",
    goals: "Doelen",
    family: "Familie",
    shared: "Gedeeld",
    settings: "Instellingen",
    group: "Groep",
    dashboard: "Dashboard",
    groupMembers: "Groepsleden",
    groupType: "Groepstype",
    groupName: "Groepsnaam",
    roommates: "Huisgenoten",
    couple: "Stel",
    member: "Lid",
    settlement: "Verrekening",
    settleDebt: "Schuld vereffenen",
    balanceBoard: "Saldooverzicht",
    youOwe: "Jij bent verschuldigd",
    owesYou: "is je verschuldigd",
    settled: "Vereffend",
    recordSettlement: "Verrekening registreren",
    splitEqual: "Gelijk verdelen",
    splitCustom: "Aangepaste bedragen",
    splitPercentage: "Op percentage",
    paidBy: "Betaald door",
    splitBetween: "Verdelen tussen",
    splitMethod: "Verdelingsmethode",
    selectMembers: "Selecteer leden",
    totalGroupSpending: "Totale groepsuitgaven",
    noGroupYet: "Nog geen groep",
    createOrJoinGroup: "Maak een groep aan of word lid om te beginnen",
    inviteCode: "Uitnodigingscode",
    showQrCode: "QR-code tonen",
    hideQrCode: "QR-code verbergen",
    scanQrCode: "QR-code scannen",
    pointCamera: "Richt je camera op de QR-code",
    cameraPermissionDenied: "Cameratoegang geweigerd. Sta toegang toe en probeer opnieuw, of typ de code handmatig.",
    cameraUnavailable: "Toegang tot camera mislukt. Typ de uitnodigingscode handmatig.",
    close: "Sluiten",
    leaveGroup: "Groep verlaten",
    confirmLeaveGroup: "Weet je zeker dat je deze groep wilt verlaten? Je persoonlijke gegevens blijven bewaard.",
    signOut: "Uitloggen",
    profile: "Profiel",
    language: "Taal",
    english: "Engels",
    french: "Frans",
    dutch: "Nederlands",
    spendingBreakdown: "Uitgavenoverzicht",
    recentActivity: "Recente activiteit",
    viewAll: "Alles bekijken",
    totalSpent: "Totaal uitgegeven",
    thisMonth: "deze maand",
    thisWeek: "deze week",
    topGoal: "Topprioriteit doel",
    noGoalsYet: "Nog geen spaardoelen",
    setGoal: "Doel instellen",
    noTransactions: "Geen transacties gevonden.",
    save: "Opslaan",
    cancel: "Annuleren",
    edit: "Bewerken",
    delete: "Verwijderen",
    profileName: "Weergavenaam",
    profileImage: "Profielafbeelding",
    changeImage: "Afbeelding wijzigen",
    settingsTitle: "Instellingen",
    spendingReflections: "Uitgavenreflecties",
    weeklyReflections: "Wekelijks overzicht",
    monthlyReflections: "Maandelijks overzicht",
    spentThisWeek: "Deze week uitgegeven",
    spentThisMonth: "Deze maand uitgegeven",
    topCategory: "Topcategorie",
    noData: "Nog geen uitgavengegevens.",
    viewSpendingReflections: "Bekijk uitgavenreflecties",
    financialSnapshot: "Hier is je financieel overzicht.",
    hi: "Hoi",
    priority: "Prioriteit",
    daysLeft: "dagen resterend",
    dueToday: "Vandaag verwacht!",
    viewAllGoals: "Alle doelen bekijken",
    categoryDetails: "Categoriedetails",
    profileUpdated: "Profiel bijgewerkt",
    changesSaved: "Je wijzigingen zijn opgeslagen.",
    error: "Fout",
    failedToUpdate: "Profiel bijwerken mislukt.",
    yourName: "Jouw naam",
    imageUrlPlaceholder: "Afbeeldings-URL (optioneel)",
    currency: "Valuta",
    scanReceipt: "Bon scannen",
    scanning: "Scannen...",
    confirmDetails: "Details bevestigen",
    extractedFromReceipt: "Geëxtraheerd uit bon",
    useThisData: "Deze gegevens gebruiken",
    tryAgain: "Opnieuw proberen",
    selectCurrency: "Selecteer je valuta",
    currencyPromptMessage: "Kies de valuta die je wilt gebruiken voor het bijhouden van uitgaven. Je kunt dit altijd wijzigen in Instellingen.",
    confirmCurrency: "Valuta bevestigen",
    dangerZone: "Gevaarzone",
    deleteAccountWarning: "Wanneer je je account verwijdert, is er geen weg terug. Al je gegevens worden permanent verwijderd.",
    deleteAccount: "Account verwijderen",
    confirmDeleteAccount: "Je account verwijderen?",
    deleteAccountPermanent: "Deze actie kan niet ongedaan worden gemaakt. Al je uitgaven, doelen en gegevens worden permanent verwijderd.",
    typeDeleteToConfirm: 'Typ "DELETE" om te bevestigen:',
    deleteAccountPermanently: "Account permanent verwijderen",
    accountDeleted: "Account verwijderd",
    accountDeletedMessage: "Je account is permanent verwijderd.",
    failedToDeleteAccount: "Account verwijderen mislukt. Probeer het opnieuw.",
    expenseCategories: "Uitgavencategorieën",
    customizeCategoriesDescription: "Pas de categorieën aan voor het bijhouden van je uitgaven. Klik op een categorie om de naam te bewerken.",
    newCategoryPlaceholder: "Nieuwe categorie toevoegen...",
    categories: "categorieën",
    resetToDefault: "Terugzetten naar standaard",
    categoriesUpdated: "Categorieën bijgewerkt",
    customizeCategoriesHint: "Pas categorieën aan in Instellingen",
    paidWith: "Betaald met",
    myMoney: "Mijn geld",
    familyMoney: "Groepsgeld",
    reports: "Rapporten",
    monthlyReport: "Maandrapport",
    weeklyReport: "Weekrapport",
    viewReports: "Rapporten bekijken",
    noExpensesInPeriod: "Geen uitgaven in deze periode",
    allCategories: "Alle categorieën",
    backToReports: "Terug naar rapporten",
    previousMonth: "Vorige maand",
    nextMonth: "Volgende maand",
    previousWeek: "Vorige week",
    nextWeek: "Volgende week",
    expensesInCategory: "Uitgaven in",
    expense: "uitgave",
    expensesPlural: "uitgaven",
    personal: "Persoonlijk",
    familyBadge: "Groep",
    familyDashboard: "Groepsdashboard",
    groupDashboard: "Groepsdashboard",
    members: "leden",
    month: "Maand",
    week: "Week",
    sharedSpending: "Gedeelde uitgaven",
    moneySourceSplit: "Verdeling geldbron",
    familyMoneySource: "Groepsgeld",
    personalMoneySource: "Persoonlijk geld",
    noSharedExpenses: "Nog geen gedeelde uitgaven",
    backToCategories: "Terug naar categorieën",
    noExpensesInCategory: "Geen uitgaven in deze categorie",
    spendingByCategory: "Uitgaven per categorie",
    familyGoals: "Groepsdoelen",
    groupGoals: "Groepsdoelen",
    recentSharedExpenses: "Recente gedeelde uitgaven",
    statusCompleted: "Voltooid",
    statusOnTrack: "Op schema",
    statusSlightlyBehind: "Iets achter",
    statusBehind: "Achter",
    priorityLabel: "Prioriteit",
    messages: "Berichten",
    savedNotes: "Opgeslagen notities",
    typeMessage: "Typ een bericht...",
    send: "Versturen",
    noMessages: "Nog geen berichten",
    startConversation: "Start een gesprek met je groep",
    addNote: "Notitie toevoegen",
    noteTitlePlaceholder: "Notitietitel (bijv. Boodschappenlijst)",
    noteContentPlaceholder: "Details (optioneel)",
    noNotes: "Geen opgeslagen notities",
    addFirstNote: "Voeg een notitie toe zoals een boodschappenlijst of herinnering",
    deleteNote: "Notitie verwijderen",
    markComplete: "Markeer als voltooid",
    markIncomplete: "Markeer als onvoltooid",
    noteDeleted: "Notitie verwijderd",
    messageSent: "Bericht verzonden",
    noteSaved: "Notitie opgeslagen",
    shoppingList: "Boodschappenlijst",
    by: "door",
    noGoals: "Nog geen gedeelde doelen",
    notifications: "Meldingen",
    dailyReminder: "Dagelijkse herinnering",
    dailyReminderDescription: "Ontvang een herinnering om je uitgaven te registreren",
    reminderTime: "Herinneringstijd",
    weeklyReminder: "Wekelijks overzicht",
    weeklyReminderDescription: "Bekijk je wekelijkse uitgaven elke zondag",
    monthlyReminder: "Maandelijks overzicht",
    monthlyReminderDescription: "Bekijk je maandelijkse uitgaven aan het einde van de maand",
    budgetAlerts: "Budgetwaarschuwingen",
    budgetAlertsDescription: "Ontvang een melding wanneer je een budgetlimiet nadert of overschrijdt",
    notificationsEnabled: "Meldingen ingeschakeld",
    notificationsDisabled: "Meldingen uitgeschakeld",
    enableNotifications: "Meldingen inschakelen",
    notificationPermissionDenied: "Toestemming voor meldingen geweigerd. Schakel in via de browserinstellingen.",
    makeAdmin: "Beheerder maken",
    removeAdmin: "Beheerder verwijderen",
    adminPromoted: "Lid gepromoveerd tot beheerder",
    adminDemoted: "Beheerdersrol verwijderd",
    maxAdminsReached: "Maximaal 2 beheerders per groep",
    confirmMakeAdmin: "Dit lid beheerder maken? Ze krijgen dezelfde rechten als jij.",
    confirmRemoveAdmin: "Beheerdersrol van dit lid verwijderen?",
    reminderUpdated: "Herinneringsinstellingen bijgewerkt",
    everydayExpenses: "Dagelijkse uitgaven",
    recurringExpenses: "Vaste uitgaven",
    recurring: "Terugkerend",
    addRecurring: "Vaste uitgave toevoegen",
    editRecurring: "Vaste uitgave bewerken",
    recurringName: "Naam",
    recurringAmount: "Bedrag",
    recurringCategory: "Groep",
    recurringFrequency: "Frequentie",
    recurringNote: "Notitie (optioneel)",
    noRecurringExpenses: "Nog geen vaste uitgaven",
    addFirstRecurring: "Volg abonnementen, rekeningen, belastingen en andere vaste kosten",
    totalRecurring: "Totaal terugkerend",
    subscriptions: "Abonnementen",
    utilities: "Nutsvoorzieningen",
    taxes: "Belastingen",
    insurance: "Verzekering",
    other: "Overig",
    monthly: "Maandelijks",
    quarterly: "Driemaandelijks",
    yearly: "Jaarlijks",
    perMonth: "/maand",
    perQuarter: "/kwartaal",
    perYear: "/jaar",
    recurringAdded: "Vaste uitgave toegevoegd",
    recurringUpdated: "Vaste uitgave bijgewerkt",
    recurringDeleted: "Vaste uitgave verwijderd",
    activeLabel: "Actief",
    pausedLabel: "Gepauzeerd",
    recurringCategoriesTitle: "Groepen vaste uitgaven",
    recurringCategoriesDescription: "Pas de groepen aan voor het organiseren van je vaste uitgaven. Klik op een groep om de naam te bewerken.",
    recurringCategoriesUpdated: "Terugkerende groepen bijgewerkt",
    newRecurringCategoryPlaceholder: "Nieuwe groep toevoegen...",
    customizeRecurringCategoriesHint: "Pas groepen aan in Instellingen",
    budgetPlanning: "Budget & Planning",
    planYourBudget: "Plan je budget",
    budgetSetupMessage: "Wil je je budgetten nu instellen, of wachten tot je een tijdje uitgaven hebt bijgehouden?",
    setupNow: "Nu instellen",
    remindWeek: "Herinner me over een week",
    remindMonth: "Herinner me over een maand",
    totalBudget: "Totaal budget",
    totalRemaining: "Totaal resterend",
    percentUsed: "gebruikt",
    spent: "Uitgegeven",
    remaining: "Resterend",
    budgetAmount: "Budgetbedrag",
    periodType: "Periode",
    weekly: "Wekelijks",
    editBudget: "Budget bewerken",
    addBudget: "Budget toevoegen",
    deleteBudget: "Budget verwijderen",
    noBudgets: "Nog geen budgetten ingesteld",
    setupFirstBudget: "Stel je eerste budget in",
    budgetAdded: "Budget toegevoegd",
    budgetUpdated: "Budget bijgewerkt",
    budgetDeleted: "Budget verwijderd",
    thresholds: "Waarschuwingsdrempels",
    threshold50: "50% gebruikt",
    threshold60: "60% gebruikt",
    threshold80: "80% gebruikt",
    threshold100: "100% gebruikt",
    budgetNote: "Budgetnotitie",
    budgetNotePlaceholder: "Planningsnotitie toevoegen...",
    averageSpending: "Gemiddelde uitgaven",
    budgetOverview: "Budgetoverzicht",
    categoryBudgets: "Budgetten per categorie",
    noBudgetSet: "Geen budget ingesteld",
    addBudgetForCategory: "Budget toevoegen",
    budgetExceeded: "Budget overschreden",
    onBudget: "Binnen budget",
    overBudget: "Boven budget",
    budgetWarning: "Budgetwaarschuwing",
    personalSpending: "Persoonlijke uitgaven",
    today: "Vandaag",
    vsLastMonth: "vs vorige maand",
    spendingActivity: "Uitgavenactiviteit",
    weeklyView: "Wekelijks",
    monthlyView: "Maandelijks",
    sun: "Zo",
    mon: "Ma",
    tue: "Di",
    wed: "Wo",
    thu: "Do",
    fri: "Vr",
    sat: "Za",
    searchExpenses: "Uitgaven zoeken...",
    noSearchResults: "Geen uitgaven gevonden voor",
    tapBarHint: "Tik op een balk om de uitgaven te zien",
    nothingSpentHere: "Hier niets uitgegeven",
    budget: "Budget",
    landingBeta: "Beta · Gratis tijdens de ontwikkeling",
    landingHeroTitle1: "Gedeelde financiën,",
    landingHeroTitle2: "eindelijk eenvoudig.",
    landingHeroSubtitle: "Volg uitgaven, splits rekeningen en beheer budgetten samen, of je nu samenwoont met familie, huisgenoten of een partner. Werkt als een app, te installeren via je browser.",
    landingHeroNote: "Begin alleen of sluit je op elk moment aan bij een groep.",
    landingOpenApp: "App openen",
    landingInstallApp: "App installeren",
    landingSignIn: "Inloggen",
    landingTrustTitle: "Gebouwd voor het echte leven, niet voor spreadsheets",
    landingTrustBody: "SharedLedger is een progressive web app, dus geen app store nodig. Voeg het in seconden toe aan je beginscherm. Deel een groepsuitnodiging of de app zelf via QR-code of link, rechtstreeks vanuit WhatsApp, iMessage of elke berichtenapp. Je gegevens worden veilig opgeslagen in de cloud.",
    landingWhyTitle: "Voor wie is SharedLedger?",
    landingWhySubtitle: "Van stellen tot huishoudens tot solo-budgetters, het past zich aan jou aan.",
    landingHowTitle: "In minuten operationeel",
    landingHowSubtitle: "Geen complexe installatie. Geen creditcard. Geen gedoe.",
    landingStep1Title: "Maak een gratis account aan",
    landingStep1Desc: "Registreer je in minder dan 30 seconden met je e-mail of Google-account. Geen betalingsinformatie vereist.",
    landingStep2Title: "Stel je groep in (optioneel)",
    landingStep2Desc: "Maak een huishouden aan of word lid door een QR-code te scannen of op een gedeelde link te tikken via WhatsApp, iMessage of elke berichtenapp. Liever solo beginnen? Geen probleem, je kunt je groep altijd later toevoegen.",
    landingStep3Title: "Voeg je eerste uitgave toe",
    landingStep3Desc: "Registreer elke aankoop direct: kies een categorie, stel een bedrag in, kies een valuta en beslis of het gedeeld of persoonlijk is.",
    landingStep4Title: "Installeer als app",
    landingStep4Desc: "Voeg SharedLedger toe aan je beginscherm voor de volledige native ervaring. Geen app store vereist. Werkt op iPhone en Android.",
    landingFeaturesTitle: "Alles wat je nodig hebt om op koers te blijven",
    landingGrowTitle: "Begin eenvoudig. Groei ermee mee.",
    landingGrowBody: "Je hoeft op dag één geen groep in te stellen. Begin met het bijhouden van je eigen uitgaven solo en de app is direct volledig bruikbaar. Wanneer je er klaar voor bent, nodig je huishouden uit met één tik.",
    landingInstallTitle: "Installeer SharedLedger op je telefoon",
    landingInstallSubtitle: "Geen app store. Geen downloads. Voeg het gewoon toe aan je beginscherm in seconden.",
    landingCurrencyTitle: "Werkt in jouw valuta",
    landingCurrencyBody: "SharedLedger ondersteunt tientallen valuta, waaronder USD, EUR, GBP, CAD, AUD, JPY, INR en nog veel meer. Je kunt je valuta op elk moment wijzigen in de instellingen.",
    landingFeedbackTitle: "Deel je gedachten",
    landingFeedbackSubtitle: "SharedLedger is in bèta. Je feedback bepaalt wat er hierna wordt gebouwd. Elk bericht wordt gelezen.",
    landingMockThisMonth: "Deze maand",
    landingMockSpentAcross: "uitgegeven door 3 leden",
    landingMockYouOwe: "Jij bent verschuldigd",
    landingMockOwedToYou: "Jou wordt verschuldigd",
    landingMockGroceries: "Boodschappen",
    landingMockUtilities: "Nutsvoorzieningen",
    landingMockDiningOut: "Uit eten",
    landingTrustSecure: "Veilig & Privé",
    landingTrustCloud: "Cloudgebaseerd",
    landingTrustCurrency: "Meerdere valuta",
    landingTrustMobile: "Mobile-First",
    landingTrustLanguages: "3 Talen",
    landingUseFamiliesTitle: "Families",
    landingUseFamiliesDesc: "Volg huishoudelijke uitgaven, stel budgetten per categorie in en houd elk gezinslid op één lijn, van ouders tot kinderen.",
    landingUseRoommatesTitle: "Huisgenoten",
    landingUseRoommatesDesc: "Verdeel huur, boodschappen en rekeningen eerlijk. Zie wie wat betaald heeft en verrekend in seconden zonder ongemakkelijke gesprekken.",
    landingUseCouplesTitle: "Stellen",
    landingUseCouplesDesc: "Beheer gedeelde uitgaven naast elkaar. Stel gezamenlijke spaardoelen in, volg de voortgang samen en blijf financieel gesynchroniseerd.",
    landingUseFriendsTitle: "Vriendengroepen",
    landingUseFriendsDesc: "Reis plannen, diners splitsen of een uitje organiseren? Maak een groep voor elke gelegenheid, volg wie wat betaald heeft en verrekend zonder giswerk.",
    landingUseSoloTitle: "Solo bijhouden",
    landingUseSoloDesc: "Deel je financiën niet met iemand? SharedLedger werkt net zo goed alleen. Log uitgaven, stel budgetten in en volg spaardoelen als persoonlijke financiële tracker.",
    landingFeature1Title: "Uitgaven bijhouden",
    landingFeature1Desc: "Registreer persoonlijke en gedeelde uitgaven met categorieën, notities en bonnen. Filter en doorzoek je geschiedenis direct.",
    landingFeature2Title: "Slimme budgetten",
    landingFeature2Desc: "Stel maandelijkse budgetten per categorie in. Kleurgecodeerde voortgangsbalken waarschuwen je voordat je overschrijdt.",
    landingFeature3Title: "Spaardoelen",
    landingFeature3Desc: "Maak doelen met streefbedragen en deadlines. Draag in de loop van de tijd bij en zie je voortgang groeien.",
    landingFeature4Title: "Visuele rapporten",
    landingFeature4Desc: "Begrijp je uitgavenpatronen in één oogopslag met grafieken, uitsplitsingen en trendanalyse.",
    landingFeature5Title: "Slimme meldingen",
    landingFeature5Desc: "Ontvang herinneringen om uitgaven te registreren en waarschuwingen wanneer budgetten je drempelwaarden bereiken. Volledig configureerbaar.",
    landingFeature6Title: "Groepsberichten",
    landingFeature6Desc: "Chat met je groep direct in de app. Bespreek uitgaven, stel vragen en blijf gesynchroniseerd.",
    landingGrowItem1Label: "Solo bijhouden",
    landingGrowItem1Detail: "Beschikbaar vanaf dag één",
    landingGrowItem2Label: "Budgetten & doelen",
    landingGrowItem2Detail: "Beschikbaar vanaf dag één",
    landingGrowItem3Label: "Groepsuitgaven & splitsen",
    landingGrowItem3Detail: "Ontgrendelt wanneer je lid wordt van een groep",
    landingGrowItem4Label: "Groepsberichten",
    landingGrowItem4Detail: "Ontgrendelt wanneer je lid wordt van een groep",
    landingGrowItem5Label: "Gezinsdashboard",
    landingGrowItem5Detail: "Ontgrendelt wanneer je lid wordt van een groep",
    landingInstallIphoneTitle: "iPhone (alleen Safari)",
    landingInstallIphoneStep1: "Link ontvangen via WhatsApp of Snapchat? Tik op ··· of het browsericoon en kies 'Openen in Safari' — dit werkt alleen in Safari",
    landingInstallIphoneStep2: "Ga in Safari naar sharedledger.app en tik op het Deelicoon (□↑). Dat staat onderaan het scherm — of rechtsboven als je de compacte adresbalk gebruikt",
    landingInstallIphoneStep3: "Scroll omlaag in het deelmenu en tik op 'Voeg toe aan beginscherm'",
    landingInstallIphoneStep4: "Tik op 'Voeg toe' rechtsboven — het app-pictogram verschijnt op je beginscherm",
    landingInstallAndroidTitle: "Android (Chrome)",
    landingInstallAndroidStep1: "Open SharedLedger in Chrome",
    landingInstallAndroidStep2: "Tik op het driepuntsmenu (⋮) rechtsboven",
    landingInstallAndroidStep3: "'Voeg toe aan beginscherm' of 'Installeer app'",
    landingInstallAndroidStep4: "Tik op 'Voeg toe' om te bevestigen en het verschijnt direct op je beginscherm",
    landingWhyInstallTitle: "Waarom installeren in plaats van gewoon de website gebruiken?",
    landingWhyInstall1Title: "Beginschermtoegang",
    landingWhyInstall1Desc: "Start direct zoals elke native app, zonder adresbalk of URL's typen.",
    landingWhyInstall2Title: "Snel laden",
    landingWhyInstall2Desc: "De app laadt direct vanaf je beginscherm zonder browseropstart.",
    landingWhyInstall3Title: "Pushmeldingen",
    landingWhyInstall3Desc: "Ontvang budgetwaarschuwingen en herinneringen voor uitgaven direct op je apparaat.",
    landingWhyInstall4Title: "Volledig scherm",
    landingWhyInstall4Desc: "Verbergt de browser-interface voor een afleidingsvrije, app-achtige ervaring.",
    landingWhyNotAppStoreTitle: "Waarom staat het niet in de App Store?",
    landingWhyNotAppStoreBody: "SharedLedger is op weg naar de App Store en Play Store, maar tijdens de bèta gebruiken we een PWA zodat we snel verbeteringen kunnen uitbrengen en direct op je feedback kunnen reageren. Geen vertragingen bij app store-goedkeuring, geen wachten op updates. Je hebt altijd de nieuwste versie zodra we die publiceren.",
    landingFeedbackAlsoIn: "Je kunt ook feedback sturen vanuit de app-instellingen zodra je bent ingelogd.",
    landingFeedbackEmail: "Of neem contact op via e-mail:",
    landingFormName: "Naam",
    landingFormNamePlaceholder: "Jouw naam",
    landingFormEmailLabel: "E-mail (optioneel)",
    landingFormEmailPlaceholder: "jij@voorbeeld.com",
    landingFormMessageLabel: "Jouw feedback",
    landingFormMessagePlaceholder: "Wat vind je geweldig? Wat mist er? Wat zou SharedLedger perfect maken voor jou?",
    landingFormSubmit: "Feedback versturen",
    landingFormThankYou: "Bedankt voor je feedback!",
    landingFormThankYouDesc: "We lezen elk bericht en waarderen dat je de tijd hebt genomen om je gedachten te delen.",
    landingComingSoonTitle: "Binnenkort beschikbaar",
    landingComingSoonSubtitle: "We bouwen actief door. Dit staat op de roadmap.",
    landingRoadmap1: "Verbeterd bonnen scannen met slimmere AI-categorisering",
    landingRoadmap2: "Optionele bankkoppeling voor automatisch importeren van uitgaven",
    landingRoadmap3: "Slimme gedeelde uitgaven",
    landingRoadmap4: "Ondersteuning voor meerdere groepen per gebruiker",
    landingRoadmap5: "Slimme analyses voor gepersonaliseerde financiële suggesties en planning",
    landingRoadmap6: "Native iOS & Android apps",
    landingCtaTitle: "Klaar om controle te nemen over je gedeelde financiën?",
    landingCtaSubtitle: "Gratis tijdens de bèta. Geen creditcard vereist. Start binnen een minuut.",
    landingCtaNote: "Begin alleen, of sluit je op elk moment aan bij een groep.",
    landingFooterText: "Bèta · Gratis terwijl we bouwen. Je feedback helpt het product vormgeven.",
    landingFooterAvailable: "Beschikbaar in het Engels, Frans en Nederlands.",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isUpdating: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<Language>((user?.language as Language) || "en");

  const updateLanguageMutation = useMutation({
    mutationFn: async (newLang: Language) => {
      const res = await apiRequest("PATCH", "/api/user/profile", { language: newLang });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/user"] });
    },
  });

  useEffect(() => {
    if (user?.language && user.language !== language) {
      setLanguageState(user.language as Language);
    }
  }, [user?.language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (user) {
      updateLanguageMutation.mutate(lang);
    }
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isUpdating: updateLanguageMutation.isPending }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
