import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { useAuth } from "@/hooks/use-auth";
import { useMutation } from "@tanstack/react-query";
import { apiRequest, queryClient } from "@/lib/queryClient";

type Language = "en" | "fr";

type TranslationKey = 
  | "home" | "expenses" | "goals" | "family" | "shared" | "settings"
  | "group" | "dashboard" | "groupMembers" | "groupType" | "groupName"
  | "roommates" | "couple" | "member"
  | "settlement" | "settleDebt" | "balanceBoard" | "youOwe" | "owesYou" | "settled" | "recordSettlement"
  | "splitEqual" | "splitCustom" | "splitPercentage" | "paidBy" | "splitBetween" | "splitMethod" | "selectMembers"
  | "totalGroupSpending" | "noGroupYet" | "createOrJoinGroup" | "inviteCode" | "leaveGroup" | "confirmLeaveGroup"
  | "signOut" | "profile" | "language" | "english" | "french"
  | "spendingBreakdown" | "recentActivity" | "viewAll" | "totalSpent"
  | "thisMonth" | "thisWeek" | "topGoal" | "noGoalsYet" | "setGoal"
  | "noTransactions" | "save" | "cancel" | "edit" | "delete"
  | "profileName" | "profileImage" | "changeImage" | "settingsTitle"
  | "spendingReflections" | "weeklyReflections" | "monthlyReflections"
  | "spentThisWeek" | "spentThisMonth" | "topCategory" | "noData"
  | "viewSpendingReflections" | "financialSnapshot" | "hi"
  | "priority" | "daysLeft" | "dueToday" | "viewAllGoals" | "categoryDetails"
  | "profileUpdated" | "changesSaved" | "error" | "failedToUpdate" | "yourName"
  | "imageUrlPlaceholder" | "currency" | "scanReceipt" | "scanning" | "confirmDetails"
  | "extractedFromReceipt" | "useThisData" | "tryAgain"
  | "selectCurrency" | "currencyPromptMessage" | "confirmCurrency"
  | "dangerZone" | "deleteAccountWarning" | "deleteAccount" | "confirmDeleteAccount"
  | "deleteAccountPermanent" | "typeDeleteToConfirm" | "deleteAccountPermanently"
  | "accountDeleted" | "accountDeletedMessage" | "failedToDeleteAccount"
  | "expenseCategories" | "customizeCategoriesDescription" | "newCategoryPlaceholder"
  | "categories" | "resetToDefault" | "categoriesUpdated" | "customizeCategoriesHint"
  | "paidWith" | "myMoney" | "familyMoney" | "reports" | "monthlyReport" | "weeklyReport"
  | "viewReports" | "noExpensesInPeriod" | "allCategories" | "backToReports"
  | "previousMonth" | "nextMonth" | "previousWeek" | "nextWeek" | "expensesInCategory"
  | "expense" | "expensesPlural" | "personal" | "familyBadge"
  | "familyDashboard" | "groupDashboard" | "members" | "month" | "week" | "sharedSpending"
  | "moneySourceSplit" | "familyMoneySource" | "personalMoneySource"
  | "noSharedExpenses" | "backToCategories" | "noExpensesInCategory"
  | "spendingByCategory" | "familyGoals" | "groupGoals" | "recentSharedExpenses"
  | "statusCompleted" | "statusOnTrack" | "statusSlightlyBehind" | "statusBehind" | "priorityLabel"
  | "messages" | "savedNotes" | "typeMessage" | "send" | "noMessages" | "startConversation"
  | "addNote" | "noteTitlePlaceholder" | "noteContentPlaceholder" | "noNotes" | "addFirstNote"
  | "deleteNote" | "markComplete" | "markIncomplete" | "noteDeleted" | "messageSent" | "noteSaved"
  | "shoppingList" | "by" | "noGoals"
  | "notifications" | "dailyReminder" | "dailyReminderDescription" | "reminderTime"
  | "weeklyReminder" | "weeklyReminderDescription" | "monthlyReminder" | "monthlyReminderDescription"
  | "budgetAlerts" | "budgetAlertsDescription"
  | "notificationsEnabled" | "notificationsDisabled" | "enableNotifications"
  | "notificationPermissionDenied" | "makeAdmin" | "removeAdmin" | "adminPromoted"
  | "adminDemoted" | "maxAdminsReached" | "confirmMakeAdmin" | "confirmRemoveAdmin" | "reminderUpdated"
  | "everydayExpenses" | "recurringExpenses" | "recurring" | "addRecurring" | "editRecurring"
  | "recurringName" | "recurringAmount" | "recurringCategory" | "recurringFrequency"
  | "recurringNote" | "noRecurringExpenses" | "addFirstRecurring" | "totalRecurring"
  | "subscriptions" | "utilities" | "taxes" | "insurance" | "other"
  | "monthly" | "quarterly" | "yearly" | "perMonth" | "perQuarter" | "perYear"
  | "recurringAdded" | "recurringUpdated" | "recurringDeleted" | "activeLabel" | "pausedLabel"
  | "recurringCategoriesTitle" | "recurringCategoriesDescription" | "recurringCategoriesUpdated"
  | "newRecurringCategoryPlaceholder" | "customizeRecurringCategoriesHint"
  | "budgetPlanning" | "planYourBudget" | "budgetSetupMessage"
  | "setupNow" | "remindWeek" | "remindMonth"
  | "totalBudget" | "totalRemaining" | "percentUsed" | "spent"
  | "remaining" | "budgetAmount" | "periodType" | "weekly"
  | "editBudget" | "addBudget" | "deleteBudget" | "noBudgets" | "setupFirstBudget"
  | "budgetAdded" | "budgetUpdated" | "budgetDeleted"
  | "thresholds" | "threshold50" | "threshold60" | "threshold80" | "threshold100"
  | "budgetNote" | "budgetNotePlaceholder" | "averageSpending"
  | "budgetOverview" | "categoryBudgets" | "noBudgetSet" | "addBudgetForCategory"
  | "budgetExceeded" | "onBudget" | "overBudget" | "budgetWarning"
  | "personalSpending" | "today" | "vsLastMonth"
  | "spendingActivity" | "weeklyView" | "monthlyView"
  | "sun" | "mon" | "tue" | "wed" | "thu" | "fri" | "sat"
  | "searchExpenses" | "noSearchResults";

const translations: Record<Language, Record<TranslationKey, string>> = {
  en: {
    home: "Home",
    expenses: "Expenses",
    goals: "Goals",
    family: "Family",
    shared: "Shared",
    settings: "Settings",
    group: "Group",
    dashboard: "Dashboard",
    groupMembers: "Group Members",
    groupType: "Group Type",
    groupName: "Group Name",
    roommates: "Roommates",
    couple: "Couple",
    member: "Member",
    settlement: "Settlement",
    settleDebt: "Settle Debt",
    balanceBoard: "Balance Board",
    youOwe: "You owe",
    owesYou: "owes you",
    settled: "Settled",
    recordSettlement: "Record Settlement",
    splitEqual: "Split Equally",
    splitCustom: "Custom Amounts",
    splitPercentage: "By Percentage",
    paidBy: "Paid by",
    splitBetween: "Split between",
    splitMethod: "Split Method",
    selectMembers: "Select members",
    totalGroupSpending: "Total Group Spending",
    noGroupYet: "No group yet",
    createOrJoinGroup: "Create or join a group to get started",
    inviteCode: "Invite Code",
    leaveGroup: "Leave Group",
    confirmLeaveGroup: "Are you sure you want to leave this group? Your personal data will be kept.",
    signOut: "Sign Out",
    profile: "Profile",
    language: "Language",
    english: "English",
    french: "French",
    spendingBreakdown: "Spending Breakdown",
    recentActivity: "Recent Activity",
    viewAll: "View All",
    totalSpent: "Total Spent",
    thisMonth: "this month",
    thisWeek: "this week",
    topGoal: "Top Goal",
    noGoalsYet: "No savings goals yet",
    setGoal: "Set a Goal",
    noTransactions: "No transactions found.",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    profileName: "Display Name",
    profileImage: "Profile Image",
    changeImage: "Change Image",
    settingsTitle: "Settings",
    spendingReflections: "Spending Reflections",
    weeklyReflections: "Weekly Summary",
    monthlyReflections: "Monthly Summary",
    spentThisWeek: "Spent This Week",
    spentThisMonth: "Spent This Month",
    topCategory: "Top Category",
    noData: "No spending data yet.",
    viewSpendingReflections: "View Spending Reflections",
    financialSnapshot: "Here's your financial snapshot.",
    hi: "Hi",
    priority: "Priority",
    daysLeft: "days left",
    dueToday: "Due today!",
    viewAllGoals: "View All Goals",
    categoryDetails: "Category Details",
    profileUpdated: "Profile updated",
    changesSaved: "Your changes have been saved.",
    error: "Error",
    failedToUpdate: "Failed to update profile.",
    yourName: "Your name",
    imageUrlPlaceholder: "Image URL (optional)",
    currency: "Currency",
    scanReceipt: "Scan Receipt",
    scanning: "Scanning...",
    confirmDetails: "Confirm Details",
    extractedFromReceipt: "Extracted from receipt",
    useThisData: "Use This Data",
    tryAgain: "Try Again",
    selectCurrency: "Select Your Currency",
    currencyPromptMessage: "Choose the currency you'll use for tracking expenses. You can change this anytime in Settings.",
    confirmCurrency: "Confirm Currency",
    dangerZone: "Danger Zone",
    deleteAccountWarning: "Once you delete your account, there is no going back. All your data will be permanently removed.",
    deleteAccount: "Delete Account",
    confirmDeleteAccount: "Delete Your Account?",
    deleteAccountPermanent: "This action cannot be undone. All your expenses, goals, and data will be permanently deleted.",
    typeDeleteToConfirm: 'Type "DELETE" to confirm:',
    deleteAccountPermanently: "Delete Account Permanently",
    accountDeleted: "Account Deleted",
    accountDeletedMessage: "Your account has been permanently deleted.",
    failedToDeleteAccount: "Failed to delete account. Please try again.",
    expenseCategories: "Expense Categories",
    customizeCategoriesDescription: "Customize the categories for tracking your expenses. Click a category to edit its name.",
    newCategoryPlaceholder: "Add new category...",
    categories: "categories",
    resetToDefault: "Reset to Default",
    categoriesUpdated: "Categories Updated",
    customizeCategoriesHint: "Customize categories in Settings",
    paidWith: "Paid With",
    myMoney: "My Money",
    familyMoney: "Group Money",
    reports: "Reports",
    monthlyReport: "Monthly Report",
    weeklyReport: "Weekly Report",
    viewReports: "View Reports",
    noExpensesInPeriod: "No expenses in this period",
    allCategories: "All Categories",
    backToReports: "Back to Reports",
    previousMonth: "Previous Month",
    nextMonth: "Next Month",
    previousWeek: "Previous Week",
    nextWeek: "Next Week",
    expensesInCategory: "Expenses in",
    expense: "expense",
    expensesPlural: "expenses",
    personal: "Personal",
    familyBadge: "Group",
    familyDashboard: "Group Dashboard",
    groupDashboard: "Group Dashboard",
    members: "members",
    month: "Month",
    week: "Week",
    sharedSpending: "Shared Spending",
    moneySourceSplit: "Money Source Split",
    familyMoneySource: "Group Money",
    personalMoneySource: "Personal Money",
    noSharedExpenses: "No shared expenses yet",
    backToCategories: "Back to Categories",
    noExpensesInCategory: "No expenses in this category",
    spendingByCategory: "Spending by Category",
    familyGoals: "Group Goals",
    groupGoals: "Group Goals",
    recentSharedExpenses: "Recent Shared Expenses",
    statusCompleted: "Completed",
    statusOnTrack: "On Track",
    statusSlightlyBehind: "Slightly Behind",
    statusBehind: "Behind",
    priorityLabel: "Priority",
    messages: "Messages",
    savedNotes: "Saved Notes",
    typeMessage: "Type a message...",
    send: "Send",
    noMessages: "No messages yet",
    startConversation: "Start a conversation with your group",
    addNote: "Add Note",
    noteTitlePlaceholder: "Note title (e.g. Shopping list)",
    noteContentPlaceholder: "Details (optional)",
    noNotes: "No saved notes",
    addFirstNote: "Add a note like a shopping list or reminder",
    deleteNote: "Delete Note",
    markComplete: "Mark complete",
    markIncomplete: "Mark incomplete",
    noteDeleted: "Note deleted",
    messageSent: "Message sent",
    noteSaved: "Note saved",
    shoppingList: "Shopping List",
    by: "by",
    noGoals: "No shared goals yet",
    notifications: "Notifications",
    dailyReminder: "Daily Expense Reminder",
    dailyReminderDescription: "Get reminded to log your expenses",
    reminderTime: "Reminder Time",
    weeklyReminder: "Weekly Summary",
    weeklyReminderDescription: "Review your weekly spending every Sunday",
    monthlyReminder: "Monthly Summary",
    monthlyReminderDescription: "Review your monthly spending at month end",
    budgetAlerts: "Budget Alerts",
    budgetAlertsDescription: "Get notified when you're close to or over a budget limit",
    notificationsEnabled: "Notifications enabled",
    notificationsDisabled: "Notifications disabled",
    enableNotifications: "Enable Notifications",
    notificationPermissionDenied: "Notification permission denied. Please enable in browser settings.",
    makeAdmin: "Make Admin",
    removeAdmin: "Remove Admin",
    adminPromoted: "Member promoted to admin",
    adminDemoted: "Admin role removed",
    maxAdminsReached: "Maximum of 2 admins per group",
    confirmMakeAdmin: "Make this member an admin? They will have the same permissions as you.",
    confirmRemoveAdmin: "Remove admin role from this member?",
    reminderUpdated: "Reminder settings updated",
    everydayExpenses: "Everyday Expenses",
    recurringExpenses: "Recurring Expenses",
    recurring: "Recurring",
    addRecurring: "Add Recurring Expense",
    editRecurring: "Edit Recurring Expense",
    recurringName: "Name",
    recurringAmount: "Amount",
    recurringCategory: "Group",
    recurringFrequency: "Frequency",
    recurringNote: "Note (optional)",
    noRecurringExpenses: "No recurring expenses yet",
    addFirstRecurring: "Track subscriptions, utilities, taxes and other fixed costs",
    totalRecurring: "Total Recurring",
    subscriptions: "Subscriptions",
    utilities: "Utilities",
    taxes: "Taxes",
    insurance: "Insurance",
    other: "Other",
    monthly: "Monthly",
    quarterly: "Quarterly",
    yearly: "Yearly",
    perMonth: "/month",
    perQuarter: "/quarter",
    perYear: "/year",
    recurringAdded: "Recurring expense added",
    recurringUpdated: "Recurring expense updated",
    recurringDeleted: "Recurring expense deleted",
    activeLabel: "Active",
    pausedLabel: "Paused",
    recurringCategoriesTitle: "Recurring Expense Groups",
    recurringCategoriesDescription: "Customize the groups for organizing your recurring expenses. Click a group to edit its name.",
    recurringCategoriesUpdated: "Recurring Groups Updated",
    newRecurringCategoryPlaceholder: "Add new group...",
    customizeRecurringCategoriesHint: "Customize groups in Settings",
    budgetPlanning: "Budget & Planning",
    planYourBudget: "Plan Your Budget",
    budgetSetupMessage: "Would you like to set up your budgets now, or after tracking your spending for a while?",
    setupNow: "Set Up Now",
    remindWeek: "Remind Me in One Week",
    remindMonth: "Remind Me in One Month",
    totalBudget: "Total Budget",
    totalRemaining: "Total Remaining",
    percentUsed: "used",
    spent: "Spent",
    remaining: "Remaining",
    budgetAmount: "Budget Amount",
    periodType: "Period",
    weekly: "Weekly",
    editBudget: "Edit Budget",
    addBudget: "Add Budget",
    deleteBudget: "Delete Budget",
    noBudgets: "No budgets set up yet",
    setupFirstBudget: "Set up your first budget",
    budgetAdded: "Budget added",
    budgetUpdated: "Budget updated",
    budgetDeleted: "Budget deleted",
    thresholds: "Alert Thresholds",
    threshold50: "50% used",
    threshold60: "60% used",
    threshold80: "80% used",
    threshold100: "100% used",
    budgetNote: "Budget Note",
    budgetNotePlaceholder: "Add a planning note...",
    averageSpending: "Average Spending",
    budgetOverview: "Budget Overview",
    categoryBudgets: "Category Budgets",
    noBudgetSet: "No budget set",
    addBudgetForCategory: "Add budget",
    budgetExceeded: "Budget exceeded",
    onBudget: "On budget",
    overBudget: "Over budget",
    budgetWarning: "Budget warning",
    personalSpending: "Personal Spending",
    today: "Today",
    vsLastMonth: "vs last month",
    spendingActivity: "Spending Activity",
    weeklyView: "Weekly",
    monthlyView: "Monthly",
    sun: "Sun",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    searchExpenses: "Search expenses...",
    noSearchResults: "No expenses matching",
  },
  fr: {
    home: "Accueil",
    expenses: "Dépenses",
    goals: "Objectifs",
    family: "Famille",
    shared: "Partagé",
    settings: "Paramètres",
    group: "Groupe",
    dashboard: "Tableau de bord",
    groupMembers: "Membres du groupe",
    groupType: "Type de groupe",
    groupName: "Nom du groupe",
    roommates: "Colocataires",
    couple: "Couple",
    member: "Membre",
    settlement: "Règlement",
    settleDebt: "Régler la dette",
    balanceBoard: "Tableau des soldes",
    youOwe: "Vous devez",
    owesYou: "vous doit",
    settled: "Réglé",
    recordSettlement: "Enregistrer un règlement",
    splitEqual: "Partager également",
    splitCustom: "Montants personnalisés",
    splitPercentage: "Par pourcentage",
    paidBy: "Payé par",
    splitBetween: "Répartir entre",
    splitMethod: "Méthode de partage",
    selectMembers: "Sélectionner les membres",
    totalGroupSpending: "Dépenses totales du groupe",
    noGroupYet: "Pas encore de groupe",
    createOrJoinGroup: "Créez ou rejoignez un groupe pour commencer",
    inviteCode: "Code d'invitation",
    leaveGroup: "Quitter le groupe",
    confirmLeaveGroup: "Êtes-vous sûr de vouloir quitter ce groupe ? Vos données personnelles seront conservées.",
    signOut: "Déconnexion",
    profile: "Profil",
    language: "Langue",
    english: "Anglais",
    french: "Français",
    spendingBreakdown: "Répartition des dépenses",
    recentActivity: "Activité récente",
    viewAll: "Voir tout",
    totalSpent: "Total dépensé",
    thisMonth: "ce mois",
    thisWeek: "cette semaine",
    topGoal: "Objectif principal",
    noGoalsYet: "Pas encore d'objectifs d'épargne",
    setGoal: "Définir un objectif",
    noTransactions: "Aucune transaction trouvée.",
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    delete: "Supprimer",
    profileName: "Nom d'affichage",
    profileImage: "Image de profil",
    changeImage: "Changer l'image",
    settingsTitle: "Paramètres",
    spendingReflections: "Réflexions sur les dépenses",
    weeklyReflections: "Résumé hebdomadaire",
    monthlyReflections: "Résumé mensuel",
    spentThisWeek: "Dépensé cette semaine",
    spentThisMonth: "Dépensé ce mois",
    topCategory: "Catégorie principale",
    noData: "Pas encore de données de dépenses.",
    viewSpendingReflections: "Voir les réflexions sur les dépenses",
    financialSnapshot: "Voici votre aperçu financier.",
    hi: "Bonjour",
    priority: "Priorité",
    daysLeft: "jours restants",
    dueToday: "Échéance aujourd'hui!",
    viewAllGoals: "Voir tous les objectifs",
    categoryDetails: "Détails par catégorie",
    profileUpdated: "Profil mis à jour",
    changesSaved: "Vos modifications ont été enregistrées.",
    error: "Erreur",
    failedToUpdate: "Impossible de mettre à jour le profil.",
    yourName: "Votre nom",
    imageUrlPlaceholder: "URL de l'image (optionnel)",
    currency: "Devise",
    scanReceipt: "Scanner le reçu",
    scanning: "Numérisation...",
    confirmDetails: "Confirmer les détails",
    extractedFromReceipt: "Extrait du reçu",
    useThisData: "Utiliser ces données",
    tryAgain: "Réessayer",
    selectCurrency: "Sélectionnez votre devise",
    currencyPromptMessage: "Choisissez la devise que vous utiliserez pour suivre vos dépenses. Vous pouvez la modifier à tout moment dans les Paramètres.",
    confirmCurrency: "Confirmer la devise",
    dangerZone: "Zone de danger",
    deleteAccountWarning: "Une fois votre compte supprimé, il n'y a pas de retour en arrière. Toutes vos données seront définitivement supprimées.",
    deleteAccount: "Supprimer le compte",
    confirmDeleteAccount: "Supprimer votre compte?",
    deleteAccountPermanent: "Cette action est irréversible. Toutes vos dépenses, objectifs et données seront définitivement supprimés.",
    typeDeleteToConfirm: 'Tapez "DELETE" pour confirmer:',
    deleteAccountPermanently: "Supprimer le compte définitivement",
    accountDeleted: "Compte supprimé",
    accountDeletedMessage: "Votre compte a été définitivement supprimé.",
    failedToDeleteAccount: "Échec de la suppression du compte. Veuillez réessayer.",
    expenseCategories: "Catégories de dépenses",
    customizeCategoriesDescription: "Personnalisez les catégories pour suivre vos dépenses. Cliquez sur une catégorie pour modifier son nom.",
    newCategoryPlaceholder: "Ajouter une catégorie...",
    categories: "catégories",
    resetToDefault: "Réinitialiser",
    categoriesUpdated: "Catégories mises à jour",
    customizeCategoriesHint: "Personnalisez les catégories dans Paramètres",
    paidWith: "Payé avec",
    myMoney: "Mon argent",
    familyMoney: "Argent du groupe",
    reports: "Rapports",
    monthlyReport: "Rapport mensuel",
    weeklyReport: "Rapport hebdomadaire",
    viewReports: "Voir les rapports",
    noExpensesInPeriod: "Aucune dépense pour cette période",
    allCategories: "Toutes les catégories",
    backToReports: "Retour aux rapports",
    previousMonth: "Mois précédent",
    nextMonth: "Mois suivant",
    previousWeek: "Semaine précédente",
    nextWeek: "Semaine suivante",
    expensesInCategory: "Dépenses en",
    expense: "dépense",
    expensesPlural: "dépenses",
    personal: "Personnel",
    familyBadge: "Groupe",
    familyDashboard: "Tableau de bord du groupe",
    groupDashboard: "Tableau de bord du groupe",
    members: "membres",
    month: "Mois",
    week: "Semaine",
    sharedSpending: "Dépenses partagées",
    moneySourceSplit: "Répartition des sources",
    familyMoneySource: "Argent du groupe",
    personalMoneySource: "Argent personnel",
    noSharedExpenses: "Pas encore de dépenses partagées",
    backToCategories: "Retour aux catégories",
    noExpensesInCategory: "Aucune dépense dans cette catégorie",
    spendingByCategory: "Dépenses par catégorie",
    familyGoals: "Objectifs du groupe",
    groupGoals: "Objectifs du groupe",
    recentSharedExpenses: "Dépenses partagées récentes",
    statusCompleted: "Terminé",
    statusOnTrack: "En bonne voie",
    statusSlightlyBehind: "Légèrement en retard",
    statusBehind: "En retard",
    priorityLabel: "Priorité",
    messages: "Messages",
    savedNotes: "Notes sauvegardées",
    typeMessage: "Écrire un message...",
    send: "Envoyer",
    noMessages: "Aucun message",
    startConversation: "Commencez une conversation avec votre groupe",
    addNote: "Ajouter une note",
    noteTitlePlaceholder: "Titre (ex. Liste de courses)",
    noteContentPlaceholder: "Détails (optionnel)",
    noNotes: "Aucune note sauvegardée",
    addFirstNote: "Ajoutez une note comme une liste de courses ou un rappel",
    deleteNote: "Supprimer la note",
    markComplete: "Marquer comme terminé",
    markIncomplete: "Marquer comme non terminé",
    noteDeleted: "Note supprimée",
    messageSent: "Message envoyé",
    noteSaved: "Note sauvegardée",
    shoppingList: "Liste de courses",
    by: "par",
    noGoals: "Pas encore d'objectifs partagés",
    notifications: "Notifications",
    dailyReminder: "Rappel quotidien des dépenses",
    dailyReminderDescription: "Recevez un rappel pour enregistrer vos dépenses",
    reminderTime: "Heure du rappel",
    weeklyReminder: "Résumé hebdomadaire",
    weeklyReminderDescription: "Consultez vos dépenses hebdomadaires chaque dimanche",
    monthlyReminder: "Résumé mensuel",
    monthlyReminderDescription: "Consultez vos dépenses mensuelles en fin de mois",
    budgetAlerts: "Alertes budgétaires",
    budgetAlertsDescription: "Soyez notifié lorsque vous approchez ou dépassez une limite budgétaire",
    notificationsEnabled: "Notifications activées",
    notificationsDisabled: "Notifications désactivées",
    enableNotifications: "Activer les notifications",
    notificationPermissionDenied: "Permission de notification refusée. Veuillez activer dans les paramètres du navigateur.",
    makeAdmin: "Nommer administrateur",
    removeAdmin: "Retirer administrateur",
    adminPromoted: "Membre promu administrateur",
    adminDemoted: "Rôle d'administrateur retiré",
    maxAdminsReached: "Maximum de 2 administrateurs par groupe",
    confirmMakeAdmin: "Nommer ce membre administrateur ? Il aura les mêmes permissions que vous.",
    confirmRemoveAdmin: "Retirer le rôle d'administrateur de ce membre ?",
    reminderUpdated: "Paramètres de rappel mis à jour",
    everydayExpenses: "Dépenses courantes",
    recurringExpenses: "Dépenses récurrentes",
    recurring: "Récurrent",
    addRecurring: "Ajouter une dépense récurrente",
    editRecurring: "Modifier la dépense récurrente",
    recurringName: "Nom",
    recurringAmount: "Montant",
    recurringCategory: "Groupe",
    recurringFrequency: "Fréquence",
    recurringNote: "Note (optionnel)",
    noRecurringExpenses: "Aucune dépense récurrente",
    addFirstRecurring: "Suivez les abonnements, factures, impôts et autres coûts fixes",
    totalRecurring: "Total récurrent",
    subscriptions: "Abonnements",
    utilities: "Services publics",
    taxes: "Impôts",
    insurance: "Assurance",
    other: "Autre",
    monthly: "Mensuel",
    quarterly: "Trimestriel",
    yearly: "Annuel",
    perMonth: "/mois",
    perQuarter: "/trimestre",
    perYear: "/an",
    recurringAdded: "Dépense récurrente ajoutée",
    recurringUpdated: "Dépense récurrente mise à jour",
    recurringDeleted: "Dépense récurrente supprimée",
    activeLabel: "Actif",
    pausedLabel: "En pause",
    recurringCategoriesTitle: "Groupes de dépenses récurrentes",
    recurringCategoriesDescription: "Personnalisez les groupes pour organiser vos dépenses récurrentes. Cliquez sur un groupe pour modifier son nom.",
    recurringCategoriesUpdated: "Groupes récurrents mis à jour",
    newRecurringCategoryPlaceholder: "Ajouter un nouveau groupe...",
    customizeRecurringCategoriesHint: "Personnaliser les groupes dans Paramètres",
    budgetPlanning: "Budget & Planification",
    planYourBudget: "Planifiez votre budget",
    budgetSetupMessage: "Souhaitez-vous configurer vos budgets maintenant ou après avoir suivi vos dépenses pendant un moment ?",
    setupNow: "Configurer maintenant",
    remindWeek: "Me rappeler dans une semaine",
    remindMonth: "Me rappeler dans un mois",
    totalBudget: "Budget total",
    totalRemaining: "Restant total",
    percentUsed: "utilisé",
    spent: "Dépensé",
    remaining: "Restant",
    budgetAmount: "Montant du budget",
    periodType: "Période",
    weekly: "Hebdomadaire",
    editBudget: "Modifier le budget",
    addBudget: "Ajouter un budget",
    deleteBudget: "Supprimer le budget",
    noBudgets: "Aucun budget configuré",
    setupFirstBudget: "Configurez votre premier budget",
    budgetAdded: "Budget ajouté",
    budgetUpdated: "Budget mis à jour",
    budgetDeleted: "Budget supprimé",
    thresholds: "Seuils d'alerte",
    threshold50: "50% utilisé",
    threshold60: "60% utilisé",
    threshold80: "80% utilisé",
    threshold100: "100% utilisé",
    budgetNote: "Note de budget",
    budgetNotePlaceholder: "Ajouter une note de planification...",
    averageSpending: "Dépenses moyennes",
    budgetOverview: "Aperçu du budget",
    categoryBudgets: "Budgets par catégorie",
    noBudgetSet: "Pas de budget défini",
    addBudgetForCategory: "Ajouter un budget",
    budgetExceeded: "Budget dépassé",
    onBudget: "Dans le budget",
    overBudget: "Hors budget",
    budgetWarning: "Alerte budget",
    personalSpending: "Dépenses personnelles",
    today: "Aujourd'hui",
    vsLastMonth: "vs mois dernier",
    spendingActivity: "Activité de dépenses",
    weeklyView: "Semaine",
    monthlyView: "Mois",
    sun: "Dim",
    mon: "Lun",
    tue: "Mar",
    wed: "Mer",
    thu: "Jeu",
    fri: "Ven",
    sat: "Sam",
    searchExpenses: "Rechercher des dépenses...",
    noSearchResults: "Aucune dépense correspondant à",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
  isUpdating: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [language, setLanguageState] = useState<Language>((user?.language as Language) || "en");

  const updateLanguageMutation = useMutation({
    mutationFn: async (newLang: Language) => {
      const res = await apiRequest("PATCH", "/api/user/profile", { language: newLang });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/user"] });
    },
  });

  useEffect(() => {
    if (user?.language && user.language !== language) {
      setLanguageState(user.language as Language);
    }
  }, [user?.language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (user) {
      updateLanguageMutation.mutate(lang);
    }
  };

  const t = (key: TranslationKey): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isUpdating: updateLanguageMutation.isPending }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
